namespace ComSupMedLibB
{
    partial class frmSocialLogbook
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            FarPoint.Win.Spread.CellType.TextCellType textCellType100 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType101 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType102 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType103 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType104 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType105 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType106 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType107 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType108 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType109 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType110 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType111 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType112 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType113 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType114 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType115 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType116 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType117 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType118 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType119 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType120 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType121 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType122 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType123 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType124 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType125 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType126 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType127 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType128 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType129 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType130 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType131 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType132 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType133 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType134 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType135 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType136 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType137 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType138 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType139 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType140 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType141 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType142 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType143 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType144 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType145 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType146 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType147 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType148 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType149 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType150 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType151 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType152 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType153 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType154 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType155 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType156 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType157 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType158 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType159 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType160 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType161 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType162 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType163 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType164 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType165 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType166 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType167 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType168 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType169 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType170 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType171 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType172 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType173 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType174 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType175 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType176 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType177 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType178 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType179 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType180 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType181 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType182 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType183 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType184 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType185 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType186 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType187 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType188 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType189 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType190 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType191 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType192 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType193 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType194 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType195 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType196 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType197 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType198 = new FarPoint.Win.Spread.CellType.TextCellType();
            this.panTitle0 = new System.Windows.Forms.Panel();
            this.btnSearch = new System.Windows.Forms.Button();
            this.btnSave = new System.Windows.Forms.Button();
            this.btnPrint = new System.Windows.Forms.Button();
            this.btnExit = new System.Windows.Forms.Button();
            this.lblTitle = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.dtpSdate = new System.Windows.Forms.DateTimePicker();
            this.label1 = new System.Windows.Forms.Label();
            this.panel2 = new System.Windows.Forms.Panel();
            this.ssView = new FarPoint.Win.Spread.FpSpread();
            this.ssView_Sheet1 = new FarPoint.Win.Spread.SheetView();
            this.panTitle0.SuspendLayout();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ssView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssView_Sheet1)).BeginInit();
            this.SuspendLayout();
            // 
            // panTitle0
            // 
            this.panTitle0.BackColor = System.Drawing.Color.White;
            this.panTitle0.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.panTitle0.Controls.Add(this.btnSearch);
            this.panTitle0.Controls.Add(this.btnSave);
            this.panTitle0.Controls.Add(this.btnPrint);
            this.panTitle0.Controls.Add(this.btnExit);
            this.panTitle0.Controls.Add(this.lblTitle);
            this.panTitle0.Dock = System.Windows.Forms.DockStyle.Top;
            this.panTitle0.ForeColor = System.Drawing.Color.White;
            this.panTitle0.Location = new System.Drawing.Point(0, 0);
            this.panTitle0.Name = "panTitle0";
            this.panTitle0.Size = new System.Drawing.Size(682, 32);
            this.panTitle0.TabIndex = 78;
            // 
            // btnSearch
            // 
            this.btnSearch.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnSearch.AutoSize = true;
            this.btnSearch.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnSearch.Location = new System.Drawing.Point(361, 0);
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.Size = new System.Drawing.Size(79, 29);
            this.btnSearch.TabIndex = 15;
            this.btnSearch.Text = "조  회";
            this.btnSearch.UseVisualStyleBackColor = true;
            this.btnSearch.Click += new System.EventHandler(this.btnSearch_Click);
            // 
            // btnSave
            // 
            this.btnSave.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnSave.AutoSize = true;
            this.btnSave.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnSave.Location = new System.Drawing.Point(440, 0);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(79, 29);
            this.btnSave.TabIndex = 15;
            this.btnSave.Text = "저  장";
            this.btnSave.UseVisualStyleBackColor = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // btnPrint
            // 
            this.btnPrint.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnPrint.AutoSize = true;
            this.btnPrint.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnPrint.Location = new System.Drawing.Point(519, 0);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.Size = new System.Drawing.Size(79, 29);
            this.btnPrint.TabIndex = 15;
            this.btnPrint.Text = "출  력";
            this.btnPrint.UseVisualStyleBackColor = true;
            this.btnPrint.Click += new System.EventHandler(this.btnPrint_Click);
            // 
            // btnExit
            // 
            this.btnExit.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnExit.AutoSize = true;
            this.btnExit.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnExit.Location = new System.Drawing.Point(598, 0);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(79, 29);
            this.btnExit.TabIndex = 15;
            this.btnExit.Text = "닫  기";
            this.btnExit.UseVisualStyleBackColor = true;
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            // 
            // lblTitle
            // 
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("맑은 고딕", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.lblTitle.ForeColor = System.Drawing.Color.Black;
            this.lblTitle.Location = new System.Drawing.Point(5, 4);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(92, 21);
            this.lblTitle.TabIndex = 14;
            this.lblTitle.Text = "업 무 일 지";
            this.lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.dtpSdate);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 32);
            this.panel1.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(682, 30);
            this.panel1.TabIndex = 79;
            // 
            // dtpSdate
            // 
            this.dtpSdate.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpSdate.Location = new System.Drawing.Point(68, 5);
            this.dtpSdate.Name = "dtpSdate";
            this.dtpSdate.Size = new System.Drawing.Size(103, 21);
            this.dtpSdate.TabIndex = 1;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(9, 9);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(53, 12);
            this.label1.TabIndex = 0;
            this.label1.Text = "조회기간";
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.ssView);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel2.Location = new System.Drawing.Point(0, 62);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(682, 659);
            this.panel2.TabIndex = 80;
            // 
            // ssView
            // 
            this.ssView.AccessibleDescription = "ssView, Sheet1, Row 0, Column 0, 상담 및\r\n정서지원\r\n서비스제공";
            this.ssView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ssView.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.ssView.Location = new System.Drawing.Point(0, 0);
            this.ssView.Name = "ssView";
            this.ssView.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.ssView_Sheet1});
            this.ssView.Size = new System.Drawing.Size(682, 659);
            this.ssView.TabIndex = 0;
            this.ssView.EditModeOff += new System.EventHandler(this.ssView_EditModeOff);
            // 
            // ssView_Sheet1
            // 
            this.ssView_Sheet1.Reset();
            this.ssView_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.ssView_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.ssView_Sheet1.ColumnCount = 6;
            this.ssView_Sheet1.RowCount = 19;
            textCellType100.Multiline = true;
            textCellType100.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(0, 0).CellType = textCellType100;
            this.ssView_Sheet1.Cells.Get(0, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 0).RowSpan = 6;
            this.ssView_Sheet1.Cells.Get(0, 0).Value = "상담 및\r\n정서지원\r\n서비스제공";
            this.ssView_Sheet1.Cells.Get(0, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType101.Multiline = true;
            textCellType101.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(0, 1).CellType = textCellType101;
            this.ssView_Sheet1.Cells.Get(0, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(0, 1).Value = "취약계층 신환자 방문 및 선별환자 재방문";
            textCellType102.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(0, 2).CellType = textCellType102;
            this.ssView_Sheet1.Cells.Get(0, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType103.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(0, 3).CellType = textCellType103;
            this.ssView_Sheet1.Cells.Get(0, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType104.Multiline = true;
            textCellType104.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(0, 4).CellType = textCellType104;
            this.ssView_Sheet1.Cells.Get(0, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(0, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType105.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(1, 0).CellType = textCellType105;
            textCellType106.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(1, 1).CellType = textCellType106;
            this.ssView_Sheet1.Cells.Get(1, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(1, 1).Value = "심리.사회.정서적 상담";
            textCellType107.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(1, 2).CellType = textCellType107;
            this.ssView_Sheet1.Cells.Get(1, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType108.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(1, 3).CellType = textCellType108;
            this.ssView_Sheet1.Cells.Get(1, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType109.Multiline = true;
            textCellType109.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(1, 4).CellType = textCellType109;
            this.ssView_Sheet1.Cells.Get(1, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(1, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType110.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(2, 0).CellType = textCellType110;
            this.ssView_Sheet1.Cells.Get(2, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(2, 1).Value = "경제적 상담";
            textCellType111.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(2, 2).CellType = textCellType111;
            this.ssView_Sheet1.Cells.Get(2, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType112.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(2, 3).CellType = textCellType112;
            this.ssView_Sheet1.Cells.Get(2, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType113.Multiline = true;
            textCellType113.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(2, 4).CellType = textCellType113;
            this.ssView_Sheet1.Cells.Get(2, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(2, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType114.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(3, 0).CellType = textCellType114;
            textCellType115.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(3, 1).CellType = textCellType115;
            this.ssView_Sheet1.Cells.Get(3, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(3, 1).Value = "입 · 퇴원 상담";
            textCellType116.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(3, 2).CellType = textCellType116;
            this.ssView_Sheet1.Cells.Get(3, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType117.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(3, 3).CellType = textCellType117;
            this.ssView_Sheet1.Cells.Get(3, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType118.Multiline = true;
            textCellType118.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(3, 4).CellType = textCellType118;
            this.ssView_Sheet1.Cells.Get(3, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(3, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType119.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(4, 0).CellType = textCellType119;
            textCellType120.Multiline = true;
            textCellType120.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(4, 1).CellType = textCellType120;
            this.ssView_Sheet1.Cells.Get(4, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(4, 1).Value = "이 · 미용 봉사/\r\n수요음악회";
            textCellType121.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(4, 2).CellType = textCellType121;
            this.ssView_Sheet1.Cells.Get(4, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType122.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(4, 3).CellType = textCellType122;
            this.ssView_Sheet1.Cells.Get(4, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType123.Multiline = true;
            textCellType123.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(4, 4).CellType = textCellType123;
            this.ssView_Sheet1.Cells.Get(4, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(4, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType124.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(5, 0).CellType = textCellType124;
            textCellType125.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(5, 1).CellType = textCellType125;
            this.ssView_Sheet1.Cells.Get(5, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(5, 1).Value = "기타";
            textCellType126.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(5, 2).CellType = textCellType126;
            this.ssView_Sheet1.Cells.Get(5, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType127.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(5, 3).CellType = textCellType127;
            this.ssView_Sheet1.Cells.Get(5, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType128.Multiline = true;
            textCellType128.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(5, 4).CellType = textCellType128;
            this.ssView_Sheet1.Cells.Get(5, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(5, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType129.Multiline = true;
            textCellType129.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(6, 0).CellType = textCellType129;
            this.ssView_Sheet1.Cells.Get(6, 0).RowSpan = 2;
            this.ssView_Sheet1.Cells.Get(6, 0).Value = "의료비\r\n지원사업";
            textCellType130.Multiline = true;
            textCellType130.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(6, 1).CellType = textCellType130;
            this.ssView_Sheet1.Cells.Get(6, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(6, 1).Value = "내부자원연결\r\n(타부서와 협력)";
            textCellType131.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(6, 2).CellType = textCellType131;
            this.ssView_Sheet1.Cells.Get(6, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(6, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType132.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(6, 3).CellType = textCellType132;
            this.ssView_Sheet1.Cells.Get(6, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(6, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType133.Multiline = true;
            textCellType133.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(6, 4).CellType = textCellType133;
            this.ssView_Sheet1.Cells.Get(6, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(6, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType134.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(7, 0).CellType = textCellType134;
            textCellType135.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(7, 1).CellType = textCellType135;
            this.ssView_Sheet1.Cells.Get(7, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(7, 1).Value = "외부자원연결";
            textCellType136.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(7, 2).CellType = textCellType136;
            this.ssView_Sheet1.Cells.Get(7, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(7, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType137.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(7, 3).CellType = textCellType137;
            this.ssView_Sheet1.Cells.Get(7, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(7, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType138.Multiline = true;
            textCellType138.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(7, 4).CellType = textCellType138;
            this.ssView_Sheet1.Cells.Get(7, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(7, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType139.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(8, 0).CellType = textCellType139;
            this.ssView_Sheet1.Cells.Get(8, 0).RowSpan = 5;
            this.ssView_Sheet1.Cells.Get(8, 0).Value = "자원봉사자";
            textCellType140.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(8, 1).CellType = textCellType140;
            this.ssView_Sheet1.Cells.Get(8, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(8, 1).Value = "교육(신입 . 친절교육)";
            textCellType141.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(8, 2).CellType = textCellType141;
            this.ssView_Sheet1.Cells.Get(8, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(8, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType142.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(8, 3).CellType = textCellType142;
            this.ssView_Sheet1.Cells.Get(8, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(8, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType143.Multiline = true;
            textCellType143.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(8, 4).CellType = textCellType143;
            this.ssView_Sheet1.Cells.Get(8, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(8, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType144.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(9, 0).CellType = textCellType144;
            textCellType145.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(9, 1).CellType = textCellType145;
            this.ssView_Sheet1.Cells.Get(9, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(9, 1).Value = "활동/VMS 관리";
            textCellType146.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(9, 2).CellType = textCellType146;
            this.ssView_Sheet1.Cells.Get(9, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(9, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType147.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(9, 3).CellType = textCellType147;
            this.ssView_Sheet1.Cells.Get(9, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(9, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType148.Multiline = true;
            textCellType148.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(9, 4).CellType = textCellType148;
            this.ssView_Sheet1.Cells.Get(9, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(9, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType149.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(10, 0).CellType = textCellType149;
            textCellType150.Multiline = true;
            textCellType150.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(10, 1).CellType = textCellType150;
            this.ssView_Sheet1.Cells.Get(10, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(10, 1).Value = "심리.정서 지원\r\n(말씀나눔 및 기념일)";
            textCellType151.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(10, 2).CellType = textCellType151;
            this.ssView_Sheet1.Cells.Get(10, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(10, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType152.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(10, 3).CellType = textCellType152;
            this.ssView_Sheet1.Cells.Get(10, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(10, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType153.Multiline = true;
            textCellType153.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(10, 4).CellType = textCellType153;
            this.ssView_Sheet1.Cells.Get(10, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(10, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType154.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(11, 0).CellType = textCellType154;
            textCellType155.Multiline = true;
            textCellType155.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(11, 1).CellType = textCellType155;
            this.ssView_Sheet1.Cells.Get(11, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(11, 1).Value = "자원봉사자 행사 및 \r\n의료비 지원";
            textCellType156.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(11, 2).CellType = textCellType156;
            this.ssView_Sheet1.Cells.Get(11, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(11, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType157.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(11, 3).CellType = textCellType157;
            this.ssView_Sheet1.Cells.Get(11, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(11, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType158.Multiline = true;
            textCellType158.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(11, 4).CellType = textCellType158;
            this.ssView_Sheet1.Cells.Get(11, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(11, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType159.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(12, 0).CellType = textCellType159;
            textCellType160.Multiline = true;
            textCellType160.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(12, 1).CellType = textCellType160;
            this.ssView_Sheet1.Cells.Get(12, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(12, 1).Value = "기타\r\n(자원봉사관련상담)";
            textCellType161.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(12, 2).CellType = textCellType161;
            this.ssView_Sheet1.Cells.Get(12, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(12, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType162.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(12, 3).CellType = textCellType162;
            this.ssView_Sheet1.Cells.Get(12, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(12, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType163.Multiline = true;
            textCellType163.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(12, 4).CellType = textCellType163;
            this.ssView_Sheet1.Cells.Get(12, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(12, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType164.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(13, 0).CellType = textCellType164;
            this.ssView_Sheet1.Cells.Get(13, 0).RowSpan = 2;
            this.ssView_Sheet1.Cells.Get(13, 0).Value = "도 서";
            textCellType165.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(13, 1).CellType = textCellType165;
            this.ssView_Sheet1.Cells.Get(13, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(13, 1).Value = "도서대출";
            textCellType166.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(13, 2).CellType = textCellType166;
            this.ssView_Sheet1.Cells.Get(13, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(13, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType167.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(13, 3).CellType = textCellType167;
            this.ssView_Sheet1.Cells.Get(13, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(13, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType168.Multiline = true;
            textCellType168.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(13, 4).CellType = textCellType168;
            this.ssView_Sheet1.Cells.Get(13, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(13, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType169.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(14, 0).CellType = textCellType169;
            textCellType170.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(14, 1).CellType = textCellType170;
            this.ssView_Sheet1.Cells.Get(14, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(14, 1).Value = "도서관리";
            textCellType171.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(14, 2).CellType = textCellType171;
            this.ssView_Sheet1.Cells.Get(14, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(14, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType172.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(14, 3).CellType = textCellType172;
            this.ssView_Sheet1.Cells.Get(14, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(14, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType173.Multiline = true;
            textCellType173.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(14, 4).CellType = textCellType173;
            this.ssView_Sheet1.Cells.Get(14, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(14, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType174.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(15, 0).CellType = textCellType174;
            this.ssView_Sheet1.Cells.Get(15, 0).RowSpan = 3;
            this.ssView_Sheet1.Cells.Get(15, 0).Value = "행 정";
            textCellType175.Multiline = true;
            textCellType175.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(15, 1).CellType = textCellType175;
            this.ssView_Sheet1.Cells.Get(15, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(15, 1).Value = "교육 및 회의\r\n(지역사회네트워크)";
            textCellType176.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(15, 2).CellType = textCellType176;
            this.ssView_Sheet1.Cells.Get(15, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(15, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType177.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(15, 3).CellType = textCellType177;
            this.ssView_Sheet1.Cells.Get(15, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(15, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType178.Multiline = true;
            textCellType178.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(15, 4).CellType = textCellType178;
            this.ssView_Sheet1.Cells.Get(15, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(15, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType179.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(16, 0).CellType = textCellType179;
            textCellType180.Multiline = true;
            textCellType180.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(16, 1).CellType = textCellType180;
            this.ssView_Sheet1.Cells.Get(16, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(16, 1).Value = "지역사회공헌\r\n(학습비지원, 불우이웃돕기, 도서바자회, 소소한 나눔, 부서별 후원금 등)";
            textCellType181.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(16, 2).CellType = textCellType181;
            this.ssView_Sheet1.Cells.Get(16, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(16, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType182.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(16, 3).CellType = textCellType182;
            this.ssView_Sheet1.Cells.Get(16, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(16, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType183.Multiline = true;
            textCellType183.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(16, 4).CellType = textCellType183;
            this.ssView_Sheet1.Cells.Get(16, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(16, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType184.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(17, 0).CellType = textCellType184;
            textCellType185.Multiline = true;
            textCellType185.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(17, 1).CellType = textCellType185;
            this.ssView_Sheet1.Cells.Get(17, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(17, 1).Value = "의료봉사활동\r\n(국내 . 외 봉사활동)";
            textCellType186.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(17, 2).CellType = textCellType186;
            this.ssView_Sheet1.Cells.Get(17, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(17, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType187.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(17, 3).CellType = textCellType187;
            this.ssView_Sheet1.Cells.Get(17, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(17, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType188.Multiline = true;
            textCellType188.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(17, 4).CellType = textCellType188;
            this.ssView_Sheet1.Cells.Get(17, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(17, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType189.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(18, 0).CellType = textCellType189;
            this.ssView_Sheet1.Cells.Get(18, 0).Value = "기타사항";
            textCellType190.Multiline = true;
            textCellType190.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(18, 1).CellType = textCellType190;
            this.ssView_Sheet1.Cells.Get(18, 1).ColumnSpan = 4;
            this.ssView_Sheet1.Cells.Get(18, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Cells.Get(18, 1).Locked = false;
            this.ssView_Sheet1.Cells.Get(18, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType191.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(18, 2).CellType = textCellType191;
            textCellType192.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(18, 3).CellType = textCellType192;
            textCellType193.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(18, 4).CellType = textCellType193;
            this.ssView_Sheet1.ColumnHeader.Cells.Get(0, 0).Value = "구 분";
            this.ssView_Sheet1.ColumnHeader.Cells.Get(0, 1).Value = "내 용";
            this.ssView_Sheet1.ColumnHeader.Cells.Get(0, 2).Value = "건";
            this.ssView_Sheet1.ColumnHeader.Cells.Get(0, 3).Value = "명";
            this.ssView_Sheet1.ColumnHeader.Cells.Get(0, 4).Value = "세부내용";
            this.ssView_Sheet1.Columns.Get(0).CellType = textCellType194;
            this.ssView_Sheet1.Columns.Get(0).Font = new System.Drawing.Font("굴림", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.ssView_Sheet1.Columns.Get(0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Columns.Get(0).Label = "구 분";
            this.ssView_Sheet1.Columns.Get(0).Locked = true;
            this.ssView_Sheet1.Columns.Get(0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Columns.Get(0).Width = 80F;
            this.ssView_Sheet1.Columns.Get(1).CellType = textCellType195;
            this.ssView_Sheet1.Columns.Get(1).Font = new System.Drawing.Font("굴림", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.ssView_Sheet1.Columns.Get(1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Columns.Get(1).Label = "내 용";
            this.ssView_Sheet1.Columns.Get(1).Locked = false;
            this.ssView_Sheet1.Columns.Get(1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Columns.Get(1).Width = 141F;
            this.ssView_Sheet1.Columns.Get(2).CellType = textCellType196;
            this.ssView_Sheet1.Columns.Get(2).Font = new System.Drawing.Font("굴림", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.ssView_Sheet1.Columns.Get(2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Columns.Get(2).Label = "건";
            this.ssView_Sheet1.Columns.Get(2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Columns.Get(2).Width = 40F;
            this.ssView_Sheet1.Columns.Get(3).CellType = textCellType197;
            this.ssView_Sheet1.Columns.Get(3).Font = new System.Drawing.Font("굴림", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.ssView_Sheet1.Columns.Get(3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Columns.Get(3).Label = "명";
            this.ssView_Sheet1.Columns.Get(3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Columns.Get(3).Width = 40F;
            this.ssView_Sheet1.Columns.Get(4).CellType = textCellType198;
            this.ssView_Sheet1.Columns.Get(4).Font = new System.Drawing.Font("굴림", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.ssView_Sheet1.Columns.Get(4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Columns.Get(4).Label = "세부내용";
            this.ssView_Sheet1.Columns.Get(4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Columns.Get(4).Width = 359F;
            this.ssView_Sheet1.Columns.Get(5).Visible = false;
            this.ssView_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.ssView_Sheet1.RowHeader.Visible = false;
            this.ssView_Sheet1.Rows.Get(0).Height = 35F;
            this.ssView_Sheet1.Rows.Get(1).Height = 35F;
            this.ssView_Sheet1.Rows.Get(2).Height = 35F;
            this.ssView_Sheet1.Rows.Get(3).Height = 35F;
            this.ssView_Sheet1.Rows.Get(4).Height = 35F;
            this.ssView_Sheet1.Rows.Get(5).Height = 35F;
            this.ssView_Sheet1.Rows.Get(6).Height = 35F;
            this.ssView_Sheet1.Rows.Get(7).Height = 35F;
            this.ssView_Sheet1.Rows.Get(8).Height = 35F;
            this.ssView_Sheet1.Rows.Get(9).Height = 35F;
            this.ssView_Sheet1.Rows.Get(10).Height = 35F;
            this.ssView_Sheet1.Rows.Get(11).Height = 35F;
            this.ssView_Sheet1.Rows.Get(12).Height = 35F;
            this.ssView_Sheet1.Rows.Get(13).Height = 35F;
            this.ssView_Sheet1.Rows.Get(14).Height = 35F;
            this.ssView_Sheet1.Rows.Get(15).Height = 35F;
            this.ssView_Sheet1.Rows.Get(16).Height = 70F;
            this.ssView_Sheet1.Rows.Get(17).Height = 35F;
            this.ssView_Sheet1.Rows.Get(18).Height = 35F;
            this.ssView_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // frmSocialLogbook
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(682, 721);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.panTitle0);
            this.Name = "frmSocialLogbook";
            this.Text = "frmSocialLogbook";
            this.Load += new System.EventHandler(this.frmSocialLogbook_Load);
            this.panTitle0.ResumeLayout(false);
            this.panTitle0.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ssView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssView_Sheet1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panTitle0;
        private System.Windows.Forms.Button btnExit;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.DateTimePicker dtpSdate;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Panel panel2;
        private FarPoint.Win.Spread.FpSpread ssView;
        private FarPoint.Win.Spread.SheetView ssView_Sheet1;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.Button btnPrint;
        private System.Windows.Forms.Button btnSearch;
    }
}