namespace ComEmrBase
{
    partial class frmTextEmrMibi
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer1 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer enhancedRowHeaderRenderer1 = new FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer enhancedColumnHeaderRenderer1 = new FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer enhancedRowHeaderRenderer2 = new FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer enhancedColumnHeaderRenderer2 = new FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer2 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer enhancedRowHeaderRenderer3 = new FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer enhancedRowHeaderRenderer4 = new FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer3 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer enhancedRowHeaderRenderer5 = new FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer enhancedColumnHeaderRenderer3 = new FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer enhancedRowHeaderRenderer6 = new FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer enhancedColumnHeaderRenderer4 = new FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer4 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer enhancedRowHeaderRenderer7 = new FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer enhancedRowHeaderRenderer8 = new FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer5 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer enhancedRowHeaderRenderer9 = new FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer enhancedColumnHeaderRenderer5 = new FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer enhancedRowHeaderRenderer10 = new FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer enhancedColumnHeaderRenderer6 = new FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer6 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer enhancedRowHeaderRenderer11 = new FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer enhancedRowHeaderRenderer12 = new FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer enhancedColumnHeaderRenderer7 = new FarPoint.Win.Spread.CellType.EnhancedColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer enhancedRowHeaderRenderer13 = new FarPoint.Win.Spread.CellType.EnhancedRowHeaderRenderer();
            FarPoint.Win.Spread.NamedStyle namedStyle1 = new FarPoint.Win.Spread.NamedStyle("BorderEx374636998399599195835", "DataAreaDefault");
            FarPoint.Win.ComplexBorder complexBorder1 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.Spread.NamedStyle namedStyle2 = new FarPoint.Win.Spread.NamedStyle("Text501636998399599355409", "DataAreaDefault");
            FarPoint.Win.ComplexBorder complexBorder2 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType1 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle3 = new FarPoint.Win.Spread.NamedStyle("Text613636998399599405272");
            FarPoint.Win.Spread.CellType.TextCellType textCellType2 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle4 = new FarPoint.Win.Spread.NamedStyle("Text1219636998399599714447");
            FarPoint.Win.Spread.CellType.TextCellType textCellType3 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle5 = new FarPoint.Win.Spread.NamedStyle("Static1465636998399599864043");
            FarPoint.Win.Spread.CellType.TextCellType textCellType4 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.TipAppearance tipAppearance1 = new FarPoint.Win.Spread.TipAppearance();
            FarPoint.Win.ComplexBorder complexBorder3 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.WindowText, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType5 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder4 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType6 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder5 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType7 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder6 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType8 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder7 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType9 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder8 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType10 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder9 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.ComplexBorder complexBorder10 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.ComplexBorder complexBorder11 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.ComplexBorder complexBorder12 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.ComplexBorder complexBorder13 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.ComplexBorder complexBorder14 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.ComplexBorder complexBorder15 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType11 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder16 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType12 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder17 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType13 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder18 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType14 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder19 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType15 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder20 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType16 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder21 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.ActiveBorder, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType17 = new FarPoint.Win.Spread.CellType.TextCellType();
            this.panTitle = new System.Windows.Forms.Panel();
            this.btnSearch = new System.Windows.Forms.Button();
            this.lblTitle = new System.Windows.Forms.Label();
            this.btnExit = new System.Windows.Forms.Button();
            this.panel1 = new System.Windows.Forms.Panel();
            this.spMibi = new FarPoint.Win.Spread.FpSpread();
            this.spMibi_Sheet1 = new FarPoint.Win.Spread.SheetView();
            this.panTitle.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.spMibi)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.spMibi_Sheet1)).BeginInit();
            this.SuspendLayout();
            columnHeaderRenderer1.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer1.DarkColor = System.Drawing.Color.White;
            columnHeaderRenderer1.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer1.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer1.Name = "columnHeaderRenderer1";
            columnHeaderRenderer1.PictureZoomEffect = false;
            columnHeaderRenderer1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer1.TextRotationAngle = 0D;
            columnHeaderRenderer1.UseVisualStyleBackColor = false;
            columnHeaderRenderer1.ZoomFactor = 1F;
            enhancedRowHeaderRenderer1.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer1.BackColor = System.Drawing.SystemColors.Control;
            enhancedRowHeaderRenderer1.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            enhancedRowHeaderRenderer1.ForeColor = System.Drawing.SystemColors.ControlText;
            enhancedRowHeaderRenderer1.Name = "enhancedRowHeaderRenderer1";
            enhancedRowHeaderRenderer1.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer1.PictureZoomEffect = false;
            enhancedRowHeaderRenderer1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            enhancedRowHeaderRenderer1.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer1.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedRowHeaderRenderer1.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer1.TextRotationAngle = 0D;
            enhancedRowHeaderRenderer1.ZoomFactor = 1F;
            enhancedColumnHeaderRenderer1.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer1.BackColor = System.Drawing.SystemColors.Control;
            enhancedColumnHeaderRenderer1.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            enhancedColumnHeaderRenderer1.ForeColor = System.Drawing.SystemColors.ControlText;
            enhancedColumnHeaderRenderer1.Name = "enhancedColumnHeaderRenderer1";
            enhancedColumnHeaderRenderer1.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer1.PictureZoomEffect = false;
            enhancedColumnHeaderRenderer1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            enhancedColumnHeaderRenderer1.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer1.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedColumnHeaderRenderer1.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer1.TextRotationAngle = 0D;
            enhancedColumnHeaderRenderer1.ZoomFactor = 1F;
            enhancedRowHeaderRenderer2.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer2.BackColor = System.Drawing.SystemColors.Control;
            enhancedRowHeaderRenderer2.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            enhancedRowHeaderRenderer2.ForeColor = System.Drawing.SystemColors.ControlText;
            enhancedRowHeaderRenderer2.Name = "enhancedRowHeaderRenderer2";
            enhancedRowHeaderRenderer2.NormalBackgroundColor = System.Drawing.Color.White;
            enhancedRowHeaderRenderer2.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer2.PictureZoomEffect = false;
            enhancedRowHeaderRenderer2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            enhancedRowHeaderRenderer2.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer2.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer2.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer2.TextRotationAngle = 0D;
            enhancedRowHeaderRenderer2.ZoomFactor = 1F;
            enhancedColumnHeaderRenderer2.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer2.Name = "enhancedColumnHeaderRenderer2";
            enhancedColumnHeaderRenderer2.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer2.PictureZoomEffect = false;
            enhancedColumnHeaderRenderer2.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer2.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedColumnHeaderRenderer2.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer2.TextRotationAngle = 0D;
            enhancedColumnHeaderRenderer2.ZoomFactor = 1F;
            columnHeaderRenderer2.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer2.DarkColor = System.Drawing.Color.White;
            columnHeaderRenderer2.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer2.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer2.Name = "columnHeaderRenderer2";
            columnHeaderRenderer2.PictureZoomEffect = false;
            columnHeaderRenderer2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer2.TextRotationAngle = 0D;
            columnHeaderRenderer2.UseVisualStyleBackColor = false;
            columnHeaderRenderer2.ZoomFactor = 1F;
            enhancedRowHeaderRenderer3.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer3.Name = "enhancedRowHeaderRenderer3";
            enhancedRowHeaderRenderer3.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer3.PictureZoomEffect = false;
            enhancedRowHeaderRenderer3.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer3.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedRowHeaderRenderer3.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer3.TextRotationAngle = 0D;
            enhancedRowHeaderRenderer3.ZoomFactor = 1F;
            enhancedRowHeaderRenderer4.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer4.BackColor = System.Drawing.SystemColors.Control;
            enhancedRowHeaderRenderer4.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            enhancedRowHeaderRenderer4.ForeColor = System.Drawing.SystemColors.ControlText;
            enhancedRowHeaderRenderer4.Name = "enhancedRowHeaderRenderer4";
            enhancedRowHeaderRenderer4.NormalBackgroundColor = System.Drawing.Color.White;
            enhancedRowHeaderRenderer4.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer4.PictureZoomEffect = false;
            enhancedRowHeaderRenderer4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            enhancedRowHeaderRenderer4.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer4.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer4.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer4.TextRotationAngle = 0D;
            enhancedRowHeaderRenderer4.ZoomFactor = 1F;
            columnHeaderRenderer3.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer3.DarkColor = System.Drawing.Color.White;
            columnHeaderRenderer3.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer3.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer3.Name = "columnHeaderRenderer3";
            columnHeaderRenderer3.PictureZoomEffect = false;
            columnHeaderRenderer3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer3.TextRotationAngle = 0D;
            columnHeaderRenderer3.UseVisualStyleBackColor = false;
            columnHeaderRenderer3.ZoomFactor = 1F;
            enhancedRowHeaderRenderer5.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer5.BackColor = System.Drawing.SystemColors.Control;
            enhancedRowHeaderRenderer5.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            enhancedRowHeaderRenderer5.ForeColor = System.Drawing.SystemColors.ControlText;
            enhancedRowHeaderRenderer5.Name = "enhancedRowHeaderRenderer5";
            enhancedRowHeaderRenderer5.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer5.PictureZoomEffect = false;
            enhancedRowHeaderRenderer5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            enhancedRowHeaderRenderer5.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer5.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedRowHeaderRenderer5.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer5.TextRotationAngle = 0D;
            enhancedRowHeaderRenderer5.ZoomFactor = 1F;
            enhancedColumnHeaderRenderer3.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer3.BackColor = System.Drawing.SystemColors.Control;
            enhancedColumnHeaderRenderer3.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            enhancedColumnHeaderRenderer3.ForeColor = System.Drawing.SystemColors.ControlText;
            enhancedColumnHeaderRenderer3.Name = "enhancedColumnHeaderRenderer3";
            enhancedColumnHeaderRenderer3.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer3.PictureZoomEffect = false;
            enhancedColumnHeaderRenderer3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            enhancedColumnHeaderRenderer3.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer3.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedColumnHeaderRenderer3.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer3.TextRotationAngle = 0D;
            enhancedColumnHeaderRenderer3.ZoomFactor = 1F;
            enhancedRowHeaderRenderer6.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer6.BackColor = System.Drawing.SystemColors.Control;
            enhancedRowHeaderRenderer6.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            enhancedRowHeaderRenderer6.ForeColor = System.Drawing.SystemColors.ControlText;
            enhancedRowHeaderRenderer6.Name = "enhancedRowHeaderRenderer6";
            enhancedRowHeaderRenderer6.NormalBackgroundColor = System.Drawing.Color.White;
            enhancedRowHeaderRenderer6.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer6.PictureZoomEffect = false;
            enhancedRowHeaderRenderer6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            enhancedRowHeaderRenderer6.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer6.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer6.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer6.TextRotationAngle = 0D;
            enhancedRowHeaderRenderer6.ZoomFactor = 1F;
            enhancedColumnHeaderRenderer4.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer4.Name = "enhancedColumnHeaderRenderer4";
            enhancedColumnHeaderRenderer4.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer4.PictureZoomEffect = false;
            enhancedColumnHeaderRenderer4.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer4.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedColumnHeaderRenderer4.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer4.TextRotationAngle = 0D;
            enhancedColumnHeaderRenderer4.ZoomFactor = 1F;
            columnHeaderRenderer4.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer4.DarkColor = System.Drawing.Color.White;
            columnHeaderRenderer4.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer4.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer4.Name = "columnHeaderRenderer4";
            columnHeaderRenderer4.PictureZoomEffect = false;
            columnHeaderRenderer4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer4.TextRotationAngle = 0D;
            columnHeaderRenderer4.UseVisualStyleBackColor = false;
            columnHeaderRenderer4.ZoomFactor = 1F;
            enhancedRowHeaderRenderer7.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer7.Name = "enhancedRowHeaderRenderer7";
            enhancedRowHeaderRenderer7.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer7.PictureZoomEffect = false;
            enhancedRowHeaderRenderer7.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer7.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedRowHeaderRenderer7.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer7.TextRotationAngle = 0D;
            enhancedRowHeaderRenderer7.ZoomFactor = 1F;
            enhancedRowHeaderRenderer8.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer8.BackColor = System.Drawing.SystemColors.Control;
            enhancedRowHeaderRenderer8.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            enhancedRowHeaderRenderer8.ForeColor = System.Drawing.SystemColors.ControlText;
            enhancedRowHeaderRenderer8.Name = "enhancedRowHeaderRenderer8";
            enhancedRowHeaderRenderer8.NormalBackgroundColor = System.Drawing.Color.White;
            enhancedRowHeaderRenderer8.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer8.PictureZoomEffect = false;
            enhancedRowHeaderRenderer8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            enhancedRowHeaderRenderer8.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer8.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer8.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer8.TextRotationAngle = 0D;
            enhancedRowHeaderRenderer8.ZoomFactor = 1F;
            columnHeaderRenderer5.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer5.DarkColor = System.Drawing.Color.White;
            columnHeaderRenderer5.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer5.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer5.Name = "columnHeaderRenderer5";
            columnHeaderRenderer5.PictureZoomEffect = false;
            columnHeaderRenderer5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer5.TextRotationAngle = 0D;
            columnHeaderRenderer5.UseVisualStyleBackColor = false;
            columnHeaderRenderer5.ZoomFactor = 1F;
            enhancedRowHeaderRenderer9.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer9.BackColor = System.Drawing.SystemColors.Control;
            enhancedRowHeaderRenderer9.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            enhancedRowHeaderRenderer9.ForeColor = System.Drawing.SystemColors.ControlText;
            enhancedRowHeaderRenderer9.Name = "enhancedRowHeaderRenderer9";
            enhancedRowHeaderRenderer9.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer9.PictureZoomEffect = false;
            enhancedRowHeaderRenderer9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            enhancedRowHeaderRenderer9.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer9.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedRowHeaderRenderer9.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer9.TextRotationAngle = 0D;
            enhancedRowHeaderRenderer9.ZoomFactor = 1F;
            enhancedColumnHeaderRenderer5.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer5.BackColor = System.Drawing.SystemColors.Control;
            enhancedColumnHeaderRenderer5.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            enhancedColumnHeaderRenderer5.ForeColor = System.Drawing.SystemColors.ControlText;
            enhancedColumnHeaderRenderer5.Name = "enhancedColumnHeaderRenderer5";
            enhancedColumnHeaderRenderer5.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer5.PictureZoomEffect = false;
            enhancedColumnHeaderRenderer5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            enhancedColumnHeaderRenderer5.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer5.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedColumnHeaderRenderer5.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer5.TextRotationAngle = 0D;
            enhancedColumnHeaderRenderer5.ZoomFactor = 1F;
            enhancedRowHeaderRenderer10.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer10.BackColor = System.Drawing.SystemColors.Control;
            enhancedRowHeaderRenderer10.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            enhancedRowHeaderRenderer10.ForeColor = System.Drawing.SystemColors.ControlText;
            enhancedRowHeaderRenderer10.Name = "enhancedRowHeaderRenderer10";
            enhancedRowHeaderRenderer10.NormalBackgroundColor = System.Drawing.Color.White;
            enhancedRowHeaderRenderer10.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer10.PictureZoomEffect = false;
            enhancedRowHeaderRenderer10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            enhancedRowHeaderRenderer10.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer10.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer10.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer10.TextRotationAngle = 0D;
            enhancedRowHeaderRenderer10.ZoomFactor = 1F;
            enhancedColumnHeaderRenderer6.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer6.Name = "enhancedColumnHeaderRenderer6";
            enhancedColumnHeaderRenderer6.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer6.PictureZoomEffect = false;
            enhancedColumnHeaderRenderer6.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer6.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedColumnHeaderRenderer6.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer6.TextRotationAngle = 0D;
            enhancedColumnHeaderRenderer6.ZoomFactor = 1F;
            columnHeaderRenderer6.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer6.DarkColor = System.Drawing.Color.White;
            columnHeaderRenderer6.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer6.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer6.Name = "columnHeaderRenderer6";
            columnHeaderRenderer6.PictureZoomEffect = false;
            columnHeaderRenderer6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer6.TextRotationAngle = 0D;
            columnHeaderRenderer6.UseVisualStyleBackColor = false;
            columnHeaderRenderer6.ZoomFactor = 1F;
            enhancedRowHeaderRenderer11.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer11.Name = "enhancedRowHeaderRenderer11";
            enhancedRowHeaderRenderer11.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer11.PictureZoomEffect = false;
            enhancedRowHeaderRenderer11.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer11.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedRowHeaderRenderer11.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer11.TextRotationAngle = 0D;
            enhancedRowHeaderRenderer11.ZoomFactor = 1F;
            enhancedRowHeaderRenderer12.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer12.BackColor = System.Drawing.SystemColors.Control;
            enhancedRowHeaderRenderer12.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            enhancedRowHeaderRenderer12.ForeColor = System.Drawing.SystemColors.ControlText;
            enhancedRowHeaderRenderer12.Name = "enhancedRowHeaderRenderer12";
            enhancedRowHeaderRenderer12.NormalBackgroundColor = System.Drawing.Color.White;
            enhancedRowHeaderRenderer12.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer12.PictureZoomEffect = false;
            enhancedRowHeaderRenderer12.RightToLeft = System.Windows.Forms.RightToLeft.No;
            enhancedRowHeaderRenderer12.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer12.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            enhancedRowHeaderRenderer12.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer12.TextRotationAngle = 0D;
            enhancedRowHeaderRenderer12.ZoomFactor = 1F;
            enhancedColumnHeaderRenderer7.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer7.Name = "enhancedColumnHeaderRenderer7";
            enhancedColumnHeaderRenderer7.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer7.PictureZoomEffect = false;
            enhancedColumnHeaderRenderer7.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedColumnHeaderRenderer7.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedColumnHeaderRenderer7.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedColumnHeaderRenderer7.TextRotationAngle = 0D;
            enhancedColumnHeaderRenderer7.ZoomFactor = 1F;
            enhancedRowHeaderRenderer13.ActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer13.Name = "enhancedRowHeaderRenderer13";
            enhancedRowHeaderRenderer13.NormalGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer13.PictureZoomEffect = false;
            enhancedRowHeaderRenderer13.SelectedActiveBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(234)))), ((int)(((byte)(253)))));
            enhancedRowHeaderRenderer13.SelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            enhancedRowHeaderRenderer13.SelectedGridLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230)))));
            enhancedRowHeaderRenderer13.TextRotationAngle = 0D;
            enhancedRowHeaderRenderer13.ZoomFactor = 1F;
            // 
            // panTitle
            // 
            this.panTitle.BackColor = System.Drawing.Color.White;
            this.panTitle.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.panTitle.Controls.Add(this.btnSearch);
            this.panTitle.Controls.Add(this.lblTitle);
            this.panTitle.Controls.Add(this.btnExit);
            this.panTitle.Dock = System.Windows.Forms.DockStyle.Top;
            this.panTitle.Location = new System.Drawing.Point(0, 0);
            this.panTitle.Name = "panTitle";
            this.panTitle.Size = new System.Drawing.Size(841, 34);
            this.panTitle.TabIndex = 13;
            // 
            // btnSearch
            // 
            this.btnSearch.BackColor = System.Drawing.Color.Transparent;
            this.btnSearch.Location = new System.Drawing.Point(690, 1);
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.Size = new System.Drawing.Size(72, 30);
            this.btnSearch.TabIndex = 32;
            this.btnSearch.Text = "조회";
            this.btnSearch.UseVisualStyleBackColor = false;
            this.btnSearch.Click += new System.EventHandler(this.btnSearch_Click);
            // 
            // lblTitle
            // 
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("맑은 고딕", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.lblTitle.Location = new System.Drawing.Point(3, 4);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(166, 21);
            this.lblTitle.TabIndex = 4;
            this.lblTitle.Text = "개인별 미비 현황조회";
            // 
            // btnExit
            // 
            this.btnExit.BackColor = System.Drawing.Color.Transparent;
            this.btnExit.Location = new System.Drawing.Point(762, 1);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(72, 30);
            this.btnExit.TabIndex = 31;
            this.btnExit.Text = "닫기";
            this.btnExit.UseVisualStyleBackColor = false;
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.spMibi);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(0, 34);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(841, 727);
            this.panel1.TabIndex = 14;
            // 
            // spMibi
            // 
            this.spMibi.AccessibleDescription = "spMibi, Sheet1, Row 0, Column 0, 99999999";
            this.spMibi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.spMibi.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.Never;
            this.spMibi.Location = new System.Drawing.Point(0, 0);
            this.spMibi.Name = "spMibi";
            namedStyle1.Border = complexBorder1;
            namedStyle1.Font = new System.Drawing.Font("굴림", 9F);
            namedStyle1.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle1.Locked = true;
            namedStyle1.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle1.Parent = "DataAreaDefault";
            namedStyle1.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            namedStyle2.Border = complexBorder2;
            textCellType1.MaxLength = 32000;
            namedStyle2.CellType = textCellType1;
            namedStyle2.Font = new System.Drawing.Font("굴림", 9F);
            namedStyle2.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle2.Locked = true;
            namedStyle2.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle2.Parent = "DataAreaDefault";
            namedStyle2.Renderer = textCellType1;
            namedStyle2.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            textCellType2.MaxLength = 32000;
            namedStyle3.CellType = textCellType2;
            namedStyle3.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle3.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle3.Renderer = textCellType2;
            namedStyle3.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType3.MaxLength = 32000;
            textCellType3.Multiline = true;
            namedStyle4.CellType = textCellType3;
            namedStyle4.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            namedStyle4.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle4.Renderer = textCellType3;
            namedStyle4.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType4.Static = true;
            textCellType4.WordWrap = true;
            namedStyle5.CellType = textCellType4;
            namedStyle5.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle5.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle5.Renderer = textCellType4;
            namedStyle5.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi.NamedStyles.AddRange(new FarPoint.Win.Spread.NamedStyle[] {
            namedStyle1,
            namedStyle2,
            namedStyle3,
            namedStyle4,
            namedStyle5});
            this.spMibi.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.spMibi_Sheet1});
            this.spMibi.Size = new System.Drawing.Size(841, 727);
            this.spMibi.TabIndex = 26;
            this.spMibi.TabStripRatio = 0.6D;
            tipAppearance1.BackColor = System.Drawing.SystemColors.Info;
            tipAppearance1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F);
            tipAppearance1.ForeColor = System.Drawing.SystemColors.InfoText;
            this.spMibi.TextTipAppearance = tipAppearance1;
            this.spMibi.VerticalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.spMibi.CellClick += new FarPoint.Win.Spread.CellClickEventHandler(this.ssMiBiList_CellClick);
            this.spMibi.CellDoubleClick += new FarPoint.Win.Spread.CellClickEventHandler(this.ssMiBiList_CellDoubleClick);
            // 
            // spMibi_Sheet1
            // 
            this.spMibi_Sheet1.Reset();
            this.spMibi_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.spMibi_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.spMibi_Sheet1.ColumnCount = 19;
            this.spMibi_Sheet1.RowCount = 1;
            this.spMibi_Sheet1.Cells.Get(0, 0).Value = "99999999";
            this.spMibi_Sheet1.Cells.Get(0, 2).Value = "9999-99-99";
            this.spMibi_Sheet1.Cells.Get(0, 3).Value = "9999-99-99";
            this.spMibi_Sheet1.ColumnFooter.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 0).Value = "등록번호";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 1).Value = "성  명";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 2).Value = "입원일";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 3).Value = "퇴원일";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 4).Value = "진료과";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 5).Value = "진료의";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 6).Value = "MedFrTime";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 7).Value = "MedEndTime";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 8).Value = "MedDeptCd";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 9).Value = "MedDrCd";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 10).Value = "Sex";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 11).Value = "Age";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 12).Value = "입/퇴원요약지";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 13).Value = "동의서";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 14).Value = "입원기록지";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 15).Value = "경과기록지";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 16).Value = "수술기록지";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 17).Value = "전과기록지";
            this.spMibi_Sheet1.ColumnHeader.Cells.Get(0, 18).Value = "시술기록지";
            this.spMibi_Sheet1.ColumnHeader.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.spMibi_Sheet1.ColumnHeader.DefaultStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.spMibi_Sheet1.ColumnHeader.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spMibi_Sheet1.ColumnHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spMibi_Sheet1.ColumnHeader.DefaultStyle.Parent = "ColumnHeaderDefaultEnhanced";
            this.spMibi_Sheet1.ColumnHeader.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spMibi_Sheet1.ColumnHeader.Rows.Get(0).Height = 37F;
            this.spMibi_Sheet1.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.spMibi_Sheet1.Columns.Get(0).Border = complexBorder3;
            textCellType5.MaxLength = 32000;
            this.spMibi_Sheet1.Columns.Get(0).CellType = textCellType5;
            this.spMibi_Sheet1.Columns.Get(0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(0).Label = "등록번호";
            this.spMibi_Sheet1.Columns.Get(0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(0).Width = 72F;
            this.spMibi_Sheet1.Columns.Get(1).Border = complexBorder4;
            textCellType6.MaxLength = 32000;
            this.spMibi_Sheet1.Columns.Get(1).CellType = textCellType6;
            this.spMibi_Sheet1.Columns.Get(1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(1).Label = "성  명";
            this.spMibi_Sheet1.Columns.Get(1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(1).Width = 65F;
            this.spMibi_Sheet1.Columns.Get(2).Border = complexBorder5;
            textCellType7.MaxLength = 32000;
            this.spMibi_Sheet1.Columns.Get(2).CellType = textCellType7;
            this.spMibi_Sheet1.Columns.Get(2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(2).Label = "입원일";
            this.spMibi_Sheet1.Columns.Get(2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(2).Width = 81F;
            this.spMibi_Sheet1.Columns.Get(3).Border = complexBorder6;
            textCellType8.MaxLength = 32000;
            textCellType8.WordWrap = true;
            this.spMibi_Sheet1.Columns.Get(3).CellType = textCellType8;
            this.spMibi_Sheet1.Columns.Get(3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(3).Label = "퇴원일";
            this.spMibi_Sheet1.Columns.Get(3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(3).Width = 81F;
            this.spMibi_Sheet1.Columns.Get(4).Border = complexBorder7;
            textCellType9.MaxLength = 32000;
            this.spMibi_Sheet1.Columns.Get(4).CellType = textCellType9;
            this.spMibi_Sheet1.Columns.Get(4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(4).Label = "진료과";
            this.spMibi_Sheet1.Columns.Get(4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(4).Visible = false;
            this.spMibi_Sheet1.Columns.Get(4).Width = 102F;
            this.spMibi_Sheet1.Columns.Get(5).Border = complexBorder8;
            textCellType10.MaxLength = 32000;
            this.spMibi_Sheet1.Columns.Get(5).CellType = textCellType10;
            this.spMibi_Sheet1.Columns.Get(5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(5).Label = "진료의";
            this.spMibi_Sheet1.Columns.Get(5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(5).Visible = false;
            this.spMibi_Sheet1.Columns.Get(5).Width = 72F;
            this.spMibi_Sheet1.Columns.Get(6).Border = complexBorder9;
            this.spMibi_Sheet1.Columns.Get(6).Label = "MedFrTime";
            this.spMibi_Sheet1.Columns.Get(6).Visible = false;
            this.spMibi_Sheet1.Columns.Get(7).Border = complexBorder10;
            this.spMibi_Sheet1.Columns.Get(7).Label = "MedEndTime";
            this.spMibi_Sheet1.Columns.Get(7).Visible = false;
            this.spMibi_Sheet1.Columns.Get(8).Border = complexBorder11;
            this.spMibi_Sheet1.Columns.Get(8).Label = "MedDeptCd";
            this.spMibi_Sheet1.Columns.Get(8).Visible = false;
            this.spMibi_Sheet1.Columns.Get(9).Border = complexBorder12;
            this.spMibi_Sheet1.Columns.Get(9).Label = "MedDrCd";
            this.spMibi_Sheet1.Columns.Get(9).Visible = false;
            this.spMibi_Sheet1.Columns.Get(10).Border = complexBorder13;
            this.spMibi_Sheet1.Columns.Get(10).Label = "Sex";
            this.spMibi_Sheet1.Columns.Get(10).Visible = false;
            this.spMibi_Sheet1.Columns.Get(11).Border = complexBorder14;
            this.spMibi_Sheet1.Columns.Get(11).Label = "Age";
            this.spMibi_Sheet1.Columns.Get(11).Visible = false;
            this.spMibi_Sheet1.Columns.Get(12).Border = complexBorder15;
            textCellType11.MaxLength = 32000;
            textCellType11.Multiline = true;
            textCellType11.WordWrap = true;
            this.spMibi_Sheet1.Columns.Get(12).CellType = textCellType11;
            this.spMibi_Sheet1.Columns.Get(12).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spMibi_Sheet1.Columns.Get(12).Label = "입/퇴원요약지";
            this.spMibi_Sheet1.Columns.Get(12).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(12).Width = 112F;
            this.spMibi_Sheet1.Columns.Get(13).Border = complexBorder16;
            textCellType12.MaxLength = 32000;
            textCellType12.Multiline = true;
            textCellType12.WordWrap = true;
            this.spMibi_Sheet1.Columns.Get(13).CellType = textCellType12;
            this.spMibi_Sheet1.Columns.Get(13).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spMibi_Sheet1.Columns.Get(13).Label = "동의서";
            this.spMibi_Sheet1.Columns.Get(13).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(13).Width = 97F;
            this.spMibi_Sheet1.Columns.Get(14).Border = complexBorder17;
            textCellType13.MaxLength = 32000;
            textCellType13.Multiline = true;
            textCellType13.WordWrap = true;
            this.spMibi_Sheet1.Columns.Get(14).CellType = textCellType13;
            this.spMibi_Sheet1.Columns.Get(14).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spMibi_Sheet1.Columns.Get(14).Label = "입원기록지";
            this.spMibi_Sheet1.Columns.Get(14).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(14).Width = 97F;
            this.spMibi_Sheet1.Columns.Get(15).Border = complexBorder18;
            textCellType14.MaxLength = 32000;
            textCellType14.Multiline = true;
            textCellType14.WordWrap = true;
            this.spMibi_Sheet1.Columns.Get(15).CellType = textCellType14;
            this.spMibi_Sheet1.Columns.Get(15).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spMibi_Sheet1.Columns.Get(15).Label = "경과기록지";
            this.spMibi_Sheet1.Columns.Get(15).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(15).Width = 97F;
            this.spMibi_Sheet1.Columns.Get(16).Border = complexBorder19;
            textCellType15.MaxLength = 32000;
            textCellType15.Multiline = true;
            textCellType15.WordWrap = true;
            this.spMibi_Sheet1.Columns.Get(16).CellType = textCellType15;
            this.spMibi_Sheet1.Columns.Get(16).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spMibi_Sheet1.Columns.Get(16).Label = "수술기록지";
            this.spMibi_Sheet1.Columns.Get(16).SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.Descending;
            this.spMibi_Sheet1.Columns.Get(16).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(16).Width = 97F;
            this.spMibi_Sheet1.Columns.Get(17).Border = complexBorder20;
            textCellType16.MaxLength = 32000;
            textCellType16.Multiline = true;
            textCellType16.WordWrap = true;
            this.spMibi_Sheet1.Columns.Get(17).CellType = textCellType16;
            this.spMibi_Sheet1.Columns.Get(17).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(17).Label = "전과기록지";
            this.spMibi_Sheet1.Columns.Get(17).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(17).Visible = false;
            this.spMibi_Sheet1.Columns.Get(17).Width = 97F;
            this.spMibi_Sheet1.Columns.Get(18).Border = complexBorder21;
            textCellType17.MaxLength = 32000;
            textCellType17.Multiline = true;
            textCellType17.WordWrap = true;
            this.spMibi_Sheet1.Columns.Get(18).CellType = textCellType17;
            this.spMibi_Sheet1.Columns.Get(18).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(18).Label = "시술기록지";
            this.spMibi_Sheet1.Columns.Get(18).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spMibi_Sheet1.Columns.Get(18).Visible = false;
            this.spMibi_Sheet1.Columns.Get(18).Width = 97F;
            this.spMibi_Sheet1.DefaultStyleName = "Text501636998399599355409";
            this.spMibi_Sheet1.GrayAreaBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.spMibi_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.spMibi_Sheet1.RowHeader.DefaultStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.spMibi_Sheet1.RowHeader.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spMibi_Sheet1.RowHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spMibi_Sheet1.RowHeader.DefaultStyle.Parent = "RowHeaderDefaultEnhanced";
            this.spMibi_Sheet1.RowHeader.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spMibi_Sheet1.Rows.Default.Height = 29F;
            this.spMibi_Sheet1.Rows.Get(0).Height = 48F;
            this.spMibi_Sheet1.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(243)))), ((int)(((byte)(188)))));
            this.spMibi_Sheet1.SelectionStyle = FarPoint.Win.Spread.SelectionStyles.SelectionColors;
            this.spMibi_Sheet1.SheetCornerStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(242)))), ((int)(((byte)(248)))));
            this.spMibi_Sheet1.SheetCornerStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spMibi_Sheet1.SheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spMibi_Sheet1.SheetCornerStyle.Parent = "CornerDefaultEnhanced";
            this.spMibi_Sheet1.SheetCornerStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spMibi_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // frmTextEmrMibi
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 17F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(841, 761);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.panTitle);
            this.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.Name = "frmTextEmrMibi";
            this.Text = "개인별 미비 현황조회";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.FrmTextEmrMibi_FormClosed);
            this.Load += new System.EventHandler(this.frmTextEmrMibi_Load);
            this.panTitle.ResumeLayout(false);
            this.panTitle.PerformLayout();
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.spMibi)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.spMibi_Sheet1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panTitle;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Button btnExit;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Button btnSearch;
        private FarPoint.Win.Spread.FpSpread spMibi;
        private FarPoint.Win.Spread.SheetView spMibi_Sheet1;
    }
}