namespace ComPmpaLibB
{
    partial class frmPmpaTongSinhwan
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            FarPoint.Win.Spread.TipAppearance tipAppearance4 = new FarPoint.Win.Spread.TipAppearance();
            FarPoint.Win.EmptyBorder emptyBorder19 = new FarPoint.Win.EmptyBorder();
            FarPoint.Win.Spread.CellType.TextCellType textCellType7 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.EmptyBorder emptyBorder20 = new FarPoint.Win.EmptyBorder();
            FarPoint.Win.Spread.CellType.TextCellType textCellType8 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle5 = new FarPoint.Win.Spread.NamedStyle("BorderEx402636390950542602280", "DataAreaDefault");
            FarPoint.Win.ComplexBorder complexBorder3 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.Spread.NamedStyle namedStyle6 = new FarPoint.Win.Spread.NamedStyle("Static506636390950542758380", "DataAreaDefault");
            FarPoint.Win.ComplexBorder complexBorder4 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType5 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle7 = new FarPoint.Win.Spread.NamedStyle("Static847636390950542758380");
            FarPoint.Win.Spread.CellType.TextCellType textCellType6 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle8 = new FarPoint.Win.Spread.NamedStyle("Color880636390950542758380");
            FarPoint.Win.Spread.TipAppearance tipAppearance3 = new FarPoint.Win.Spread.TipAppearance();
            FarPoint.Win.EmptyBorder emptyBorder11 = new FarPoint.Win.EmptyBorder();
            FarPoint.Win.EmptyBorder emptyBorder12 = new FarPoint.Win.EmptyBorder();
            FarPoint.Win.EmptyBorder emptyBorder13 = new FarPoint.Win.EmptyBorder();
            FarPoint.Win.EmptyBorder emptyBorder14 = new FarPoint.Win.EmptyBorder();
            FarPoint.Win.EmptyBorder emptyBorder15 = new FarPoint.Win.EmptyBorder();
            FarPoint.Win.EmptyBorder emptyBorder16 = new FarPoint.Win.EmptyBorder();
            FarPoint.Win.EmptyBorder emptyBorder17 = new FarPoint.Win.EmptyBorder();
            FarPoint.Win.EmptyBorder emptyBorder18 = new FarPoint.Win.EmptyBorder();
            this.panTitleSub0 = new System.Windows.Forms.Panel();
            this.lblTitleSub0 = new System.Windows.Forms.Label();
            this.panTitle = new System.Windows.Forms.Panel();
            this.btnView = new System.Windows.Forms.Button();
            this.label15 = new System.Windows.Forms.Label();
            this.btnExit = new System.Windows.Forms.Button();
            this.dtpTDate = new System.Windows.Forms.DateTimePicker();
            this.dtpFDate = new System.Windows.Forms.DateTimePicker();
            this.panel1 = new System.Windows.Forms.Panel();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.panel2 = new System.Windows.Forms.Panel();
            this.label1 = new System.Windows.Forms.Label();
            this.tabControl1 = new DevComponents.DotNetBar.TabControl();
            this.tabControlPanel1 = new DevComponents.DotNetBar.TabControlPanel();
            this.ssList1 = new FarPoint.Win.Spread.FpSpread();
            this.ssList1_Sheet1 = new FarPoint.Win.Spread.SheetView();
            this.tabItem1 = new DevComponents.DotNetBar.TabItem(this.components);
            this.tabControlPanel2 = new DevComponents.DotNetBar.TabControlPanel();
            this.tabItem2 = new DevComponents.DotNetBar.TabItem(this.components);
            this.tabItem3 = new DevComponents.DotNetBar.TabItem(this.components);
            this.tabControlPanel3 = new DevComponents.DotNetBar.TabControlPanel();
            this.ssList3 = new FarPoint.Win.Spread.FpSpread();
            this.ssList3_Sheet1 = new FarPoint.Win.Spread.SheetView();
            this.ssList2 = new FarPoint.Win.Spread.FpSpread();
            this.ssList2_Sheet1 = new FarPoint.Win.Spread.SheetView();
            this.panTitleSub0.SuspendLayout();
            this.panTitle.SuspendLayout();
            this.panel1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.tabControl1)).BeginInit();
            this.tabControl1.SuspendLayout();
            this.tabControlPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ssList1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssList1_Sheet1)).BeginInit();
            this.tabControlPanel2.SuspendLayout();
            this.tabControlPanel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ssList3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssList3_Sheet1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssList2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssList2_Sheet1)).BeginInit();
            this.SuspendLayout();
            // 
            // panTitleSub0
            // 
            this.panTitleSub0.BackColor = System.Drawing.Color.RoyalBlue;
            this.panTitleSub0.Controls.Add(this.lblTitleSub0);
            this.panTitleSub0.Dock = System.Windows.Forms.DockStyle.Top;
            this.panTitleSub0.Location = new System.Drawing.Point(0, 36);
            this.panTitleSub0.Name = "panTitleSub0";
            this.panTitleSub0.Size = new System.Drawing.Size(972, 28);
            this.panTitleSub0.TabIndex = 117;
            // 
            // lblTitleSub0
            // 
            this.lblTitleSub0.AutoSize = true;
            this.lblTitleSub0.BackColor = System.Drawing.Color.Transparent;
            this.lblTitleSub0.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.lblTitleSub0.ForeColor = System.Drawing.Color.White;
            this.lblTitleSub0.Location = new System.Drawing.Point(12, 6);
            this.lblTitleSub0.Name = "lblTitleSub0";
            this.lblTitleSub0.Size = new System.Drawing.Size(65, 17);
            this.lblTitleSub0.TabIndex = 22;
            this.lblTitleSub0.Text = "조회 옵션";
            this.lblTitleSub0.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // panTitle
            // 
            this.panTitle.BackColor = System.Drawing.Color.White;
            this.panTitle.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.panTitle.Controls.Add(this.label15);
            this.panTitle.Dock = System.Windows.Forms.DockStyle.Top;
            this.panTitle.ForeColor = System.Drawing.Color.White;
            this.panTitle.Location = new System.Drawing.Point(0, 0);
            this.panTitle.Name = "panTitle";
            this.panTitle.Size = new System.Drawing.Size(972, 36);
            this.panTitle.TabIndex = 116;
            // 
            // btnView
            // 
            this.btnView.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnView.AutoSize = true;
            this.btnView.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnView.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.btnView.Location = new System.Drawing.Point(816, 5);
            this.btnView.Name = "btnView";
            this.btnView.Size = new System.Drawing.Size(74, 42);
            this.btnView.TabIndex = 115;
            this.btnView.Text = "자료조회";
            this.btnView.UseVisualStyleBackColor = true;
            // 
            // label15
            // 
            this.label15.AutoSize = true;
            this.label15.Font = new System.Drawing.Font("맑은 고딕", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.label15.ForeColor = System.Drawing.Color.Black;
            this.label15.Location = new System.Drawing.Point(9, 7);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(134, 21);
            this.label15.TabIndex = 83;
            this.label15.Text = "원무팀 신환 통계";
            this.label15.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // btnExit
            // 
            this.btnExit.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnExit.AutoSize = true;
            this.btnExit.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnExit.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.btnExit.Location = new System.Drawing.Point(893, 5);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(72, 42);
            this.btnExit.TabIndex = 15;
            this.btnExit.Text = "닫기";
            this.btnExit.UseVisualStyleBackColor = true;
            // 
            // dtpTDate
            // 
            this.dtpTDate.CustomFormat = "yyyy-MM-dd";
            this.dtpTDate.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpTDate.Location = new System.Drawing.Point(97, 12);
            this.dtpTDate.Name = "dtpTDate";
            this.dtpTDate.Size = new System.Drawing.Size(85, 21);
            this.dtpTDate.TabIndex = 120;
            // 
            // dtpFDate
            // 
            this.dtpFDate.CustomFormat = "yyyy-MM-dd";
            this.dtpFDate.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpFDate.Location = new System.Drawing.Point(6, 12);
            this.dtpFDate.Name = "dtpFDate";
            this.dtpFDate.Size = new System.Drawing.Size(85, 21);
            this.dtpFDate.TabIndex = 118;
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.btnView);
            this.panel1.Controls.Add(this.btnExit);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 64);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(972, 52);
            this.panel1.TabIndex = 123;
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.dtpFDate);
            this.groupBox2.Controls.Add(this.dtpTDate);
            this.groupBox2.Location = new System.Drawing.Point(15, 72);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(187, 39);
            this.groupBox2.TabIndex = 23;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "조회기간";
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.RoyalBlue;
            this.panel2.Controls.Add(this.label1);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel2.Location = new System.Drawing.Point(0, 116);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(972, 28);
            this.panel2.TabIndex = 124;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(12, 6);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(65, 17);
            this.label1.TabIndex = 22;
            this.label1.Text = "조회 결과";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // tabControl1
            // 
            this.tabControl1.BackColor = System.Drawing.Color.White;
            this.tabControl1.CanReorderTabs = true;
            this.tabControl1.Controls.Add(this.tabControlPanel2);
            this.tabControl1.Controls.Add(this.tabControlPanel3);
            this.tabControl1.Controls.Add(this.tabControlPanel1);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(0, 144);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedTabFont = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Bold);
            this.tabControl1.SelectedTabIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(972, 492);
            this.tabControl1.TabIndex = 125;
            this.tabControl1.TabLayoutType = DevComponents.DotNetBar.eTabLayoutType.FixedWithNavigationBox;
            this.tabControl1.Tabs.Add(this.tabItem1);
            this.tabControl1.Tabs.Add(this.tabItem2);
            this.tabControl1.Tabs.Add(this.tabItem3);
            this.tabControl1.Text = "tabControl1";
            // 
            // tabControlPanel1
            // 
            this.tabControlPanel1.Controls.Add(this.ssList1);
            this.tabControlPanel1.DisabledBackColor = System.Drawing.Color.Empty;
            this.tabControlPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControlPanel1.Location = new System.Drawing.Point(0, 26);
            this.tabControlPanel1.Name = "tabControlPanel1";
            this.tabControlPanel1.Padding = new System.Windows.Forms.Padding(1);
            this.tabControlPanel1.Size = new System.Drawing.Size(854, 342);
            this.tabControlPanel1.Style.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(179)))), ((int)(((byte)(231)))));
            this.tabControlPanel1.Style.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(237)))), ((int)(((byte)(254)))));
            this.tabControlPanel1.Style.Border = DevComponents.DotNetBar.eBorderType.SingleLine;
            this.tabControlPanel1.Style.BorderColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(97)))), ((int)(((byte)(156)))));
            this.tabControlPanel1.Style.BorderSide = ((DevComponents.DotNetBar.eBorderSide)(((DevComponents.DotNetBar.eBorderSide.Left | DevComponents.DotNetBar.eBorderSide.Right) 
            | DevComponents.DotNetBar.eBorderSide.Bottom)));
            this.tabControlPanel1.Style.GradientAngle = 90;
            this.tabControlPanel1.TabIndex = 1;
            this.tabControlPanel1.TabItem = this.tabItem1;
            // 
            // ssList1
            // 
            this.ssList1.AccessibleDescription = "ssList1, Sheet1, Row 0, Column 0, 일자";
            this.ssList1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ssList1.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.ssList1.Location = new System.Drawing.Point(1, 1);
            this.ssList1.Name = "ssList1";
            this.ssList1.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.ssList1_Sheet1});
            this.ssList1.Size = new System.Drawing.Size(852, 340);
            this.ssList1.TabIndex = 0;
            this.ssList1.TabStripRatio = 0.6D;
            tipAppearance4.BackColor = System.Drawing.SystemColors.Info;
            tipAppearance4.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F);
            tipAppearance4.ForeColor = System.Drawing.SystemColors.InfoText;
            this.ssList1.TextTipAppearance = tipAppearance4;
            // 
            // ssList1_Sheet1
            // 
            this.ssList1_Sheet1.Reset();
            this.ssList1_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.ssList1_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.ssList1_Sheet1.ColumnCount = 2;
            this.ssList1_Sheet1.RowCount = 8;
            this.ssList1_Sheet1.Cells.Get(0, 0).Value = "일자";
            this.ssList1_Sheet1.Cells.Get(0, 1).StyleName = "Static1043636390949891784572";
            this.ssList1_Sheet1.Cells.Get(0, 1).Value = "인원수";
            this.ssList1_Sheet1.Cells.Get(1, 1).StyleName = "Static1043636390949891784572";
            this.ssList1_Sheet1.Cells.Get(2, 0).StyleName = "Static1043636390949891784572";
            this.ssList1_Sheet1.ColumnFooter.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.ssList1_Sheet1.ColumnFooter.Columns.Default.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList1_Sheet1.ColumnFooter.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList1_Sheet1.ColumnFooter.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList1_Sheet1.ColumnFooter.DefaultStyle.Parent = "ColumnHeaderDefaultEnhanced";
            this.ssList1_Sheet1.ColumnFooter.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList1_Sheet1.ColumnFooter.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList1_Sheet1.ColumnFooter.Rows.Default.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList1_Sheet1.ColumnFooterSheetCornerStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList1_Sheet1.ColumnFooterSheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList1_Sheet1.ColumnFooterSheetCornerStyle.Parent = "CornerDefaultEnhanced";
            this.ssList1_Sheet1.ColumnFooterSheetCornerStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList1_Sheet1.ColumnFooterSheetCornerStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList1_Sheet1.ColumnHeader.Cells.Get(0, 0).Value = "일자";
            this.ssList1_Sheet1.ColumnHeader.Cells.Get(0, 1).Value = "인원수";
            this.ssList1_Sheet1.ColumnHeader.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.ssList1_Sheet1.ColumnHeader.Columns.Default.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList1_Sheet1.ColumnHeader.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList1_Sheet1.ColumnHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList1_Sheet1.ColumnHeader.DefaultStyle.Parent = "ColumnHeaderDefaultEnhanced";
            this.ssList1_Sheet1.ColumnHeader.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList1_Sheet1.ColumnHeader.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList1_Sheet1.ColumnHeader.Rows.Default.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList1_Sheet1.ColumnHeader.Rows.Get(0).Height = 32F;
            this.ssList1_Sheet1.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.ssList1_Sheet1.Columns.Get(0).BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(187)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.ssList1_Sheet1.Columns.Get(0).Border = emptyBorder19;
            textCellType7.Static = true;
            this.ssList1_Sheet1.Columns.Get(0).CellType = textCellType7;
            this.ssList1_Sheet1.Columns.Get(0).Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.ssList1_Sheet1.Columns.Get(0).ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.ssList1_Sheet1.Columns.Get(0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList1_Sheet1.Columns.Get(0).Label = "일자";
            this.ssList1_Sheet1.Columns.Get(0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList1_Sheet1.Columns.Get(0).Width = 84F;
            this.ssList1_Sheet1.Columns.Get(1).Border = emptyBorder20;
            textCellType8.Static = true;
            this.ssList1_Sheet1.Columns.Get(1).CellType = textCellType8;
            this.ssList1_Sheet1.Columns.Get(1).Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.ssList1_Sheet1.Columns.Get(1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList1_Sheet1.Columns.Get(1).Label = "인원수";
            this.ssList1_Sheet1.Columns.Get(1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList1_Sheet1.Columns.Get(1).Width = 81F;
            this.ssList1_Sheet1.FilterBar.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList1_Sheet1.FilterBar.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList1_Sheet1.FilterBar.DefaultStyle.Parent = "FilterBarDefaultEnhanced";
            this.ssList1_Sheet1.FilterBar.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList1_Sheet1.FilterBar.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList1_Sheet1.FilterBarHeaderStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList1_Sheet1.FilterBarHeaderStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList1_Sheet1.FilterBarHeaderStyle.Parent = "RowHeaderDefaultEnhanced";
            this.ssList1_Sheet1.FilterBarHeaderStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList1_Sheet1.FilterBarHeaderStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList1_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.ssList1_Sheet1.RowHeader.Columns.Default.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList1_Sheet1.RowHeader.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList1_Sheet1.RowHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList1_Sheet1.RowHeader.DefaultStyle.Parent = "RowHeaderDefaultEnhanced";
            this.ssList1_Sheet1.RowHeader.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList1_Sheet1.RowHeader.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList1_Sheet1.RowHeader.Rows.Default.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList1_Sheet1.Rows.Get(0).Height = 25F;
            this.ssList1_Sheet1.Rows.Get(1).Height = 25F;
            this.ssList1_Sheet1.Rows.Get(2).Height = 25F;
            this.ssList1_Sheet1.Rows.Get(3).Height = 25F;
            this.ssList1_Sheet1.Rows.Get(4).Height = 25F;
            this.ssList1_Sheet1.Rows.Get(5).Height = 25F;
            this.ssList1_Sheet1.Rows.Get(6).Height = 25F;
            this.ssList1_Sheet1.Rows.Get(7).Height = 25F;
            this.ssList1_Sheet1.SheetCornerStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList1_Sheet1.SheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList1_Sheet1.SheetCornerStyle.Parent = "CornerDefaultEnhanced";
            this.ssList1_Sheet1.SheetCornerStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList1_Sheet1.SheetCornerStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList1_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // tabItem1
            // 
            this.tabItem1.AttachedControl = this.tabControlPanel1;
            this.tabItem1.Name = "tabItem1";
            this.tabItem1.Text = "일자별 신환통계";
            // 
            // tabControlPanel2
            // 
            this.tabControlPanel2.Controls.Add(this.ssList2);
            this.tabControlPanel2.DisabledBackColor = System.Drawing.Color.Empty;
            this.tabControlPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControlPanel2.Location = new System.Drawing.Point(0, 26);
            this.tabControlPanel2.Name = "tabControlPanel2";
            this.tabControlPanel2.Padding = new System.Windows.Forms.Padding(1);
            this.tabControlPanel2.Size = new System.Drawing.Size(972, 466);
            this.tabControlPanel2.Style.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(179)))), ((int)(((byte)(231)))));
            this.tabControlPanel2.Style.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(237)))), ((int)(((byte)(254)))));
            this.tabControlPanel2.Style.Border = DevComponents.DotNetBar.eBorderType.SingleLine;
            this.tabControlPanel2.Style.BorderColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(97)))), ((int)(((byte)(156)))));
            this.tabControlPanel2.Style.BorderSide = ((DevComponents.DotNetBar.eBorderSide)(((DevComponents.DotNetBar.eBorderSide.Left | DevComponents.DotNetBar.eBorderSide.Right) 
            | DevComponents.DotNetBar.eBorderSide.Bottom)));
            this.tabControlPanel2.Style.GradientAngle = 90;
            this.tabControlPanel2.TabIndex = 5;
            this.tabControlPanel2.TabItem = this.tabItem2;
            // 
            // tabItem2
            // 
            this.tabItem2.AttachedControl = this.tabControlPanel2;
            this.tabItem2.Name = "tabItem2";
            this.tabItem2.Text = "기간별 과별 통계";
            // 
            // tabItem3
            // 
            this.tabItem3.AttachedControl = this.tabControlPanel3;
            this.tabItem3.Name = "tabItem3";
            this.tabItem3.Text = "상세내역";
            // 
            // tabControlPanel3
            // 
            this.tabControlPanel3.Controls.Add(this.ssList3);
            this.tabControlPanel3.DisabledBackColor = System.Drawing.Color.Empty;
            this.tabControlPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControlPanel3.Location = new System.Drawing.Point(0, 26);
            this.tabControlPanel3.Name = "tabControlPanel3";
            this.tabControlPanel3.Padding = new System.Windows.Forms.Padding(1);
            this.tabControlPanel3.Size = new System.Drawing.Size(854, 342);
            this.tabControlPanel3.Style.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(142)))), ((int)(((byte)(179)))), ((int)(((byte)(231)))));
            this.tabControlPanel3.Style.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(237)))), ((int)(((byte)(254)))));
            this.tabControlPanel3.Style.Border = DevComponents.DotNetBar.eBorderType.SingleLine;
            this.tabControlPanel3.Style.BorderColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(59)))), ((int)(((byte)(97)))), ((int)(((byte)(156)))));
            this.tabControlPanel3.Style.BorderSide = ((DevComponents.DotNetBar.eBorderSide)(((DevComponents.DotNetBar.eBorderSide.Left | DevComponents.DotNetBar.eBorderSide.Right) 
            | DevComponents.DotNetBar.eBorderSide.Bottom)));
            this.tabControlPanel3.Style.GradientAngle = 90;
            this.tabControlPanel3.TabIndex = 16;
            this.tabControlPanel3.TabItem = this.tabItem3;
            // 
            // ssList3
            // 
            this.ssList3.AccessibleDescription = "ssList3, Sheet1, Row 0, Column 0, 2016-06-01";
            this.ssList3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ssList3.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.Never;
            this.ssList3.Location = new System.Drawing.Point(1, 1);
            this.ssList3.Name = "ssList3";
            namedStyle5.Border = complexBorder3;
            namedStyle5.Font = new System.Drawing.Font("굴림", 9F);
            namedStyle5.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle5.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle5.Parent = "DataAreaDefault";
            namedStyle5.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            namedStyle6.Border = complexBorder4;
            textCellType5.Static = true;
            namedStyle6.CellType = textCellType5;
            namedStyle6.Font = new System.Drawing.Font("굴림", 9F);
            namedStyle6.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle6.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle6.Parent = "DataAreaDefault";
            namedStyle6.Renderer = textCellType5;
            namedStyle6.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType6.Static = true;
            namedStyle7.CellType = textCellType6;
            namedStyle7.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle7.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle7.Renderer = textCellType6;
            namedStyle7.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle8.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(219)))), ((int)(((byte)(202)))));
            namedStyle8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            namedStyle8.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle8.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle8.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList3.NamedStyles.AddRange(new FarPoint.Win.Spread.NamedStyle[] {
            namedStyle5,
            namedStyle6,
            namedStyle7,
            namedStyle8});
            this.ssList3.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.ssList3_Sheet1});
            this.ssList3.Size = new System.Drawing.Size(852, 340);
            this.ssList3.TabIndex = 1;
            this.ssList3.TabStripRatio = 0.6D;
            tipAppearance3.BackColor = System.Drawing.SystemColors.Info;
            tipAppearance3.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F);
            tipAppearance3.ForeColor = System.Drawing.SystemColors.InfoText;
            this.ssList3.TextTipAppearance = tipAppearance3;
            this.ssList3.VerticalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            // 
            // ssList3_Sheet1
            // 
            this.ssList3_Sheet1.Reset();
            this.ssList3_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.ssList3_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.ssList3_Sheet1.ColumnCount = 8;
            this.ssList3_Sheet1.Cells.Get(0, 0).Value = "2016-06-01";
            this.ssList3_Sheet1.Cells.Get(0, 1).Value = "MG";
            this.ssList3_Sheet1.Cells.Get(0, 2).Value = "테스트의사";
            this.ssList3_Sheet1.Cells.Get(0, 3).Value = "81000004";
            this.ssList3_Sheet1.Cells.Get(0, 4).Value = "테스트환자";
            this.ssList3_Sheet1.Cells.Get(0, 5).Value = "M/99";
            this.ssList3_Sheet1.Cells.Get(0, 6).Value = "M/99";
            this.ssList3_Sheet1.Cells.Get(0, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList3_Sheet1.Cells.Get(0, 7).Value = "12";
            this.ssList3_Sheet1.Cells.Get(0, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList3_Sheet1.ColumnFooter.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.ssList3_Sheet1.ColumnFooter.Columns.Default.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList3_Sheet1.ColumnFooter.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList3_Sheet1.ColumnFooter.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList3_Sheet1.ColumnFooter.DefaultStyle.Parent = "ColumnHeaderDefaultEnhanced";
            this.ssList3_Sheet1.ColumnFooter.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList3_Sheet1.ColumnFooter.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList3_Sheet1.ColumnFooter.Rows.Default.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList3_Sheet1.ColumnFooterSheetCornerStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList3_Sheet1.ColumnFooterSheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList3_Sheet1.ColumnFooterSheetCornerStyle.Parent = "CornerDefaultEnhanced";
            this.ssList3_Sheet1.ColumnFooterSheetCornerStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList3_Sheet1.ColumnFooterSheetCornerStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList3_Sheet1.ColumnHeader.Cells.Get(0, 0).Value = "내원일자";
            this.ssList3_Sheet1.ColumnHeader.Cells.Get(0, 1).Value = "진료과";
            this.ssList3_Sheet1.ColumnHeader.Cells.Get(0, 2).Value = "진료의사";
            this.ssList3_Sheet1.ColumnHeader.Cells.Get(0, 3).Value = "등록번호";
            this.ssList3_Sheet1.ColumnHeader.Cells.Get(0, 4).Value = "성명";
            this.ssList3_Sheet1.ColumnHeader.Cells.Get(0, 5).Value = "성별";
            this.ssList3_Sheet1.ColumnHeader.Cells.Get(0, 6).Value = "나이";
            this.ssList3_Sheet1.ColumnHeader.Cells.Get(0, 7).Value = "자격";
            this.ssList3_Sheet1.ColumnHeader.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.ssList3_Sheet1.ColumnHeader.Columns.Default.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList3_Sheet1.ColumnHeader.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList3_Sheet1.ColumnHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList3_Sheet1.ColumnHeader.DefaultStyle.Parent = "ColumnHeaderDefaultEnhanced";
            this.ssList3_Sheet1.ColumnHeader.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList3_Sheet1.ColumnHeader.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList3_Sheet1.ColumnHeader.Rows.Default.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList3_Sheet1.ColumnHeader.Rows.Get(0).Height = 33F;
            this.ssList3_Sheet1.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.ssList3_Sheet1.Columns.Get(0).AllowAutoFilter = true;
            this.ssList3_Sheet1.Columns.Get(0).AllowAutoSort = true;
            this.ssList3_Sheet1.Columns.Get(0).Border = emptyBorder11;
            this.ssList3_Sheet1.Columns.Get(0).Font = new System.Drawing.Font("맑은 고딕", 9.75F);
            this.ssList3_Sheet1.Columns.Get(0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList3_Sheet1.Columns.Get(0).Label = "내원일자";
            this.ssList3_Sheet1.Columns.Get(0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList3_Sheet1.Columns.Get(0).Width = 96F;
            this.ssList3_Sheet1.Columns.Get(1).AllowAutoFilter = true;
            this.ssList3_Sheet1.Columns.Get(1).AllowAutoSort = true;
            this.ssList3_Sheet1.Columns.Get(1).Border = emptyBorder12;
            this.ssList3_Sheet1.Columns.Get(1).Font = new System.Drawing.Font("맑은 고딕", 9.75F);
            this.ssList3_Sheet1.Columns.Get(1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList3_Sheet1.Columns.Get(1).Label = "진료과";
            this.ssList3_Sheet1.Columns.Get(1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList3_Sheet1.Columns.Get(1).Width = 92F;
            this.ssList3_Sheet1.Columns.Get(2).AllowAutoFilter = true;
            this.ssList3_Sheet1.Columns.Get(2).AllowAutoSort = true;
            this.ssList3_Sheet1.Columns.Get(2).Border = emptyBorder13;
            this.ssList3_Sheet1.Columns.Get(2).Font = new System.Drawing.Font("맑은 고딕", 9.75F);
            this.ssList3_Sheet1.Columns.Get(2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList3_Sheet1.Columns.Get(2).Label = "진료의사";
            this.ssList3_Sheet1.Columns.Get(2).Width = 95F;
            this.ssList3_Sheet1.Columns.Get(3).AllowAutoFilter = true;
            this.ssList3_Sheet1.Columns.Get(3).AllowAutoSort = true;
            this.ssList3_Sheet1.Columns.Get(3).Border = emptyBorder14;
            this.ssList3_Sheet1.Columns.Get(3).Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.ssList3_Sheet1.Columns.Get(3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList3_Sheet1.Columns.Get(3).Label = "등록번호";
            this.ssList3_Sheet1.Columns.Get(3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList3_Sheet1.Columns.Get(3).Width = 95F;
            this.ssList3_Sheet1.Columns.Get(4).AllowAutoFilter = true;
            this.ssList3_Sheet1.Columns.Get(4).AllowAutoSort = true;
            this.ssList3_Sheet1.Columns.Get(4).Border = emptyBorder15;
            this.ssList3_Sheet1.Columns.Get(4).Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.ssList3_Sheet1.Columns.Get(4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList3_Sheet1.Columns.Get(4).Label = "성명";
            this.ssList3_Sheet1.Columns.Get(4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList3_Sheet1.Columns.Get(4).Width = 79F;
            this.ssList3_Sheet1.Columns.Get(5).AllowAutoFilter = true;
            this.ssList3_Sheet1.Columns.Get(5).AllowAutoSort = true;
            this.ssList3_Sheet1.Columns.Get(5).Border = emptyBorder16;
            this.ssList3_Sheet1.Columns.Get(5).Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.ssList3_Sheet1.Columns.Get(5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList3_Sheet1.Columns.Get(5).Label = "성별";
            this.ssList3_Sheet1.Columns.Get(5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList3_Sheet1.Columns.Get(5).Width = 63F;
            this.ssList3_Sheet1.Columns.Get(6).AllowAutoFilter = true;
            this.ssList3_Sheet1.Columns.Get(6).AllowAutoSort = true;
            this.ssList3_Sheet1.Columns.Get(6).Border = emptyBorder17;
            this.ssList3_Sheet1.Columns.Get(6).Font = new System.Drawing.Font("맑은 고딕", 9.75F);
            this.ssList3_Sheet1.Columns.Get(6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList3_Sheet1.Columns.Get(6).Label = "나이";
            this.ssList3_Sheet1.Columns.Get(6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList3_Sheet1.Columns.Get(6).Width = 63F;
            this.ssList3_Sheet1.Columns.Get(7).AllowAutoFilter = true;
            this.ssList3_Sheet1.Columns.Get(7).AllowAutoSort = true;
            this.ssList3_Sheet1.Columns.Get(7).Border = emptyBorder18;
            this.ssList3_Sheet1.Columns.Get(7).Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.ssList3_Sheet1.Columns.Get(7).Label = "자격";
            this.ssList3_Sheet1.Columns.Get(7).Width = 63F;
            this.ssList3_Sheet1.FilterBar.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList3_Sheet1.FilterBar.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList3_Sheet1.FilterBar.DefaultStyle.Parent = "FilterBarDefaultEnhanced";
            this.ssList3_Sheet1.FilterBar.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList3_Sheet1.FilterBar.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList3_Sheet1.FilterBarHeaderStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList3_Sheet1.FilterBarHeaderStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList3_Sheet1.FilterBarHeaderStyle.Parent = "RowHeaderDefaultEnhanced";
            this.ssList3_Sheet1.FilterBarHeaderStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList3_Sheet1.FilterBarHeaderStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList3_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.ssList3_Sheet1.RowHeader.Columns.Default.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList3_Sheet1.RowHeader.Columns.Get(0).AllowAutoSort = true;
            this.ssList3_Sheet1.RowHeader.Columns.Get(0).Width = 40F;
            this.ssList3_Sheet1.RowHeader.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList3_Sheet1.RowHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList3_Sheet1.RowHeader.DefaultStyle.Parent = "RowHeaderDefaultEnhanced";
            this.ssList3_Sheet1.RowHeader.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList3_Sheet1.RowHeader.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList3_Sheet1.RowHeader.Rows.Default.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList3_Sheet1.Rows.Default.Height = 17F;
            this.ssList3_Sheet1.Rows.Get(0).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(1).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(2).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(3).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(4).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(5).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(6).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(7).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(8).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(9).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(10).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(11).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(12).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(13).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(14).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(15).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(16).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(17).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(18).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(19).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(20).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(21).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(22).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(23).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(24).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(25).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(26).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(27).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(28).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(29).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(30).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(31).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(32).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(33).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(34).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(35).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(36).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(37).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(38).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(39).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(40).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(41).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(42).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(43).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(44).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(45).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(46).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(47).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(48).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(49).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(50).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(51).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(52).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(53).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(54).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(55).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(56).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(57).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(58).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(59).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(60).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(61).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(62).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(63).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(64).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(65).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(66).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(67).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(68).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(69).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(70).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(71).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(72).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(73).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(74).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(75).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(76).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(77).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(78).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(79).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(80).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(81).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(82).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(83).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(84).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(85).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(86).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(87).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(88).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(89).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(90).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(91).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(92).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(93).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(94).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(95).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(96).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(97).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(98).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(99).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(100).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(101).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(102).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(103).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(104).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(105).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(106).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(107).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(108).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(109).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(110).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(111).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(112).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(113).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(114).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(115).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(116).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(117).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(118).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(119).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(120).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(121).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(122).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(123).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(124).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(125).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(126).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(127).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(128).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(129).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(130).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(131).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(132).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(133).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(134).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(135).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(136).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(137).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(138).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(139).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(140).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(141).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(142).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(143).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(144).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(145).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(146).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(147).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(148).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(149).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(150).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(151).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(152).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(153).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(154).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(155).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(156).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(157).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(158).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(159).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(160).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(161).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(162).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(163).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(164).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(165).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(166).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(167).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(168).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(169).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(170).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(171).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(172).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(173).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(174).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(175).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(176).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(177).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(178).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(179).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(180).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(181).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(182).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(183).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(184).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(185).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(186).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(187).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(188).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(189).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(190).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(191).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(192).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(193).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(194).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(195).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(196).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(197).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(198).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(199).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(200).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(201).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(202).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(203).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(204).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(205).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(206).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(207).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(208).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(209).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(210).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(211).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(212).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(213).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(214).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(215).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(216).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(217).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(218).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(219).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(220).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(221).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(222).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(223).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(224).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(225).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(226).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(227).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(228).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(229).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(230).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(231).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(232).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(233).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(234).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(235).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(236).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(237).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(238).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(239).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(240).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(241).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(242).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(243).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(244).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(245).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(246).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(247).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(248).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(249).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(250).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(251).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(252).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(253).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(254).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(255).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(256).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(257).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(258).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(259).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(260).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(261).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(262).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(263).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(264).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(265).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(266).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(267).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(268).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(269).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(270).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(271).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(272).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(273).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(274).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(275).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(276).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(277).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(278).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(279).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(280).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(281).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(282).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(283).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(284).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(285).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(286).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(287).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(288).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(289).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(290).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(291).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(292).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(293).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(294).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(295).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(296).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(297).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(298).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(299).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(300).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(301).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(302).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(303).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(304).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(305).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(306).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(307).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(308).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(309).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(310).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(311).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(312).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(313).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(314).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(315).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(316).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(317).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(318).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(319).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(320).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(321).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(322).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(323).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(324).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(325).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(326).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(327).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(328).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(329).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(330).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(331).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(332).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(333).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(334).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(335).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(336).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(337).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(338).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(339).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(340).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(341).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(342).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(343).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(344).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(345).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(346).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(347).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(348).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(349).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(350).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(351).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(352).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(353).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(354).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(355).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(356).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(357).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(358).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(359).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(360).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(361).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(362).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(363).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(364).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(365).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(366).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(367).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(368).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(369).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(370).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(371).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(372).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(373).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(374).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(375).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(376).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(377).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(378).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(379).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(380).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(381).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(382).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(383).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(384).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(385).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(386).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(387).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(388).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(389).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(390).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(391).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(392).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(393).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(394).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(395).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(396).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(397).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(398).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(399).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(400).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(401).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(402).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(403).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(404).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(405).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(406).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(407).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(408).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(409).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(410).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(411).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(412).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(413).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(414).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(415).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(416).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(417).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(418).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(419).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(420).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(421).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(422).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(423).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(424).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(425).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(426).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(427).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(428).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(429).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(430).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(431).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(432).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(433).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(434).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(435).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(436).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(437).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(438).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(439).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(440).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(441).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(442).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(443).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(444).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(445).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(446).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(447).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(448).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(449).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(450).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(451).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(452).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(453).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(454).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(455).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(456).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(457).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(458).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(459).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(460).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(461).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(462).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(463).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(464).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(465).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(466).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(467).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(468).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(469).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(470).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(471).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(472).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(473).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(474).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(475).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(476).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(477).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(478).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(479).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(480).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(481).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(482).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(483).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(484).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(485).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(486).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(487).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(488).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(489).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(490).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(491).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(492).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(493).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(494).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(495).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(496).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(497).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(498).Height = 24F;
            this.ssList3_Sheet1.Rows.Get(499).Height = 24F;
            this.ssList3_Sheet1.SheetCornerStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.ssList3_Sheet1.SheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.ssList3_Sheet1.SheetCornerStyle.Parent = "CornerDefaultEnhanced";
            this.ssList3_Sheet1.SheetCornerStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.ssList3_Sheet1.SheetCornerStyle.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.ssList3_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // ssList2
            // 
            this.ssList2.AccessibleDescription = "fpSpread1, Sheet1, Row 0, Column 0, 내원일자";
            this.ssList2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ssList2.Location = new System.Drawing.Point(1, 1);
            this.ssList2.Name = "ssList2";
            this.ssList2.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.ssList2_Sheet1});
            this.ssList2.Size = new System.Drawing.Size(970, 464);
            this.ssList2.TabIndex = 0;
            // 
            // ssList2_Sheet1
            // 
            this.ssList2_Sheet1.Reset();
            this.ssList2_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.ssList2_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.ssList2_Sheet1.ColumnCount = 30;
            this.ssList2_Sheet1.RowCount = 30;
            this.ssList2_Sheet1.Cells.Get(0, 0).Value = "내원일자";
            this.ssList2_Sheet1.ColumnHeader.Visible = false;
            this.ssList2_Sheet1.Columns.Get(0).BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(234)))), ((int)(((byte)(240)))));
            this.ssList2_Sheet1.Columns.Get(0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(0).Width = 79F;
            this.ssList2_Sheet1.Columns.Get(1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(9).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(9).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(10).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(10).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(11).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(11).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(12).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(12).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(13).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(13).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(14).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(14).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(15).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(15).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(16).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(16).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(17).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(17).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(18).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(18).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(19).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(19).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(20).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(20).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(21).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(21).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(22).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(22).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(23).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(23).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(24).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(24).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(25).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(25).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(26).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(26).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(27).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(27).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(28).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(28).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(29).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssList2_Sheet1.Columns.Get(29).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssList2_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.ssList2_Sheet1.RowHeader.Visible = false;
            this.ssList2_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // frmPmpaTongSinhwan
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(972, 636);
            this.Controls.Add(this.tabControl1);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.panTitleSub0);
            this.Controls.Add(this.panTitle);
            this.Name = "frmPmpaTongSinhwan";
            this.Text = "원무팀 신환통계";
            this.panTitleSub0.ResumeLayout(false);
            this.panTitleSub0.PerformLayout();
            this.panTitle.ResumeLayout(false);
            this.panTitle.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.tabControl1)).EndInit();
            this.tabControl1.ResumeLayout(false);
            this.tabControlPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ssList1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssList1_Sheet1)).EndInit();
            this.tabControlPanel2.ResumeLayout(false);
            this.tabControlPanel3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ssList3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssList3_Sheet1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssList2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssList2_Sheet1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panTitleSub0;
        private System.Windows.Forms.Label lblTitleSub0;
        private System.Windows.Forms.Panel panTitle;
        private System.Windows.Forms.Button btnView;
        private System.Windows.Forms.Label label15;
        public System.Windows.Forms.Button btnExit;
        private System.Windows.Forms.DateTimePicker dtpTDate;
        private System.Windows.Forms.DateTimePicker dtpFDate;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Label label1;
        private DevComponents.DotNetBar.TabControl tabControl1;
        private DevComponents.DotNetBar.TabControlPanel tabControlPanel2;
        private DevComponents.DotNetBar.TabItem tabItem2;
        private DevComponents.DotNetBar.TabControlPanel tabControlPanel1;
        private FarPoint.Win.Spread.FpSpread ssList1;
        private FarPoint.Win.Spread.SheetView ssList1_Sheet1;
        private DevComponents.DotNetBar.TabItem tabItem1;
        private DevComponents.DotNetBar.TabControlPanel tabControlPanel3;
        private DevComponents.DotNetBar.TabItem tabItem3;
        private FarPoint.Win.Spread.FpSpread ssList3;
        private FarPoint.Win.Spread.SheetView ssList3_Sheet1;
        private FarPoint.Win.Spread.FpSpread ssList2;
        private FarPoint.Win.Spread.SheetView ssList2_Sheet1;
    }
}