namespace ComEmrBase
{
    partial class frmEmrBaseRRSDetail
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            FarPoint.Win.ComplexBorder complexBorder1 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType1 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder2 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType2 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder3 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType3 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder4 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType4 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder5 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType5 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder6 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType6 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder7 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType7 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder8 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType8 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder9 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType9 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder10 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType10 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder11 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType11 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder12 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType12 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder13 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType13 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder14 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType14 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder15 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType15 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder16 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType16 = new FarPoint.Win.Spread.CellType.TextCellType();
            System.Globalization.CultureInfo cultureInfo = new System.Globalization.CultureInfo("ko-KR", false);
            FarPoint.Win.ComplexBorder complexBorder17 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType17 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder18 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType18 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder19 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType19 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder20 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType20 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder21 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType21 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder22 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType22 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder23 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType23 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder24 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType24 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder25 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType25 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder26 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType26 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder27 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType27 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder28 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType28 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder29 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType29 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder30 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType30 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder31 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType31 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder32 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType32 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder33 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType33 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder34 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType34 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder35 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType35 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder36 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType36 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder37 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType37 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder38 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType38 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder39 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType39 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder40 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType40 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder41 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType41 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder42 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType42 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder43 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType43 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder44 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType44 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder45 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType45 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder46 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType46 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder47 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType47 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder48 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType48 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder49 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType49 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder50 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType50 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder51 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType51 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder52 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType52 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder53 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType53 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder54 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType54 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder55 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType55 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder56 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType56 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder57 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType57 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder58 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType58 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder59 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType59 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder60 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType60 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder61 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType61 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder62 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType62 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder63 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType63 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder64 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType64 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder65 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(false, System.Drawing.SystemColors.WindowText, 1, System.Drawing.Drawing2D.DashStyle.Solid, new float[0], new float[0]), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType65 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder66 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType66 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder67 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.ComplexBorder complexBorder68 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.ComplexBorder complexBorder69 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.ComplexBorder complexBorder70 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.ComplexBorder complexBorder71 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            FarPoint.Win.ComplexBorder complexBorder72 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(System.Drawing.SystemColors.WindowText), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine), false, false);
            this.panMain = new System.Windows.Forms.Panel();
            this.fpSpread1 = new FarPoint.Win.Spread.FpSpread();
            this.sheetView1 = new FarPoint.Win.Spread.SheetView();
            this.ssView = new FarPoint.Win.Spread.FpSpread();
            this.ssView_Sheet1 = new FarPoint.Win.Spread.SheetView();
            this.panMain.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.fpSpread1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.sheetView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssView_Sheet1)).BeginInit();
            this.SuspendLayout();
            // 
            // panMain
            // 
            this.panMain.Controls.Add(this.fpSpread1);
            this.panMain.Controls.Add(this.ssView);
            this.panMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panMain.Location = new System.Drawing.Point(0, 0);
            this.panMain.Name = "panMain";
            this.panMain.Size = new System.Drawing.Size(687, 379);
            this.panMain.TabIndex = 0;
            // 
            // fpSpread1
            // 
            this.fpSpread1.AccessibleDescription = "fpSpread1, Sheet1, Row 0, Column 0, 점수";
            this.fpSpread1.Dock = System.Windows.Forms.DockStyle.Top;
            this.fpSpread1.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.Never;
            this.fpSpread1.Location = new System.Drawing.Point(0, 225);
            this.fpSpread1.Name = "fpSpread1";
            this.fpSpread1.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.sheetView1});
            this.fpSpread1.Size = new System.Drawing.Size(687, 155);
            this.fpSpread1.TabIndex = 1;
            this.fpSpread1.VerticalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.Never;
            // 
            // sheetView1
            // 
            this.sheetView1.Reset();
            this.sheetView1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.sheetView1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.sheetView1.ColumnCount = 4;
            this.sheetView1.RowCount = 4;
            this.sheetView1.Cells.Get(0, 0).BackColor = System.Drawing.Color.Gainsboro;
            this.sheetView1.Cells.Get(0, 0).Border = complexBorder1;
            this.sheetView1.Cells.Get(0, 0).CellType = textCellType1;
            this.sheetView1.Cells.Get(0, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.sheetView1.Cells.Get(0, 0).Locked = true;
            this.sheetView1.Cells.Get(0, 0).Value = "점수";
            this.sheetView1.Cells.Get(0, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(0, 1).BackColor = System.Drawing.Color.Gainsboro;
            this.sheetView1.Cells.Get(0, 1).Border = complexBorder2;
            textCellType2.WordWrap = true;
            this.sheetView1.Cells.Get(0, 1).CellType = textCellType2;
            this.sheetView1.Cells.Get(0, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.sheetView1.Cells.Get(0, 1).Locked = true;
            this.sheetView1.Cells.Get(0, 1).Value = "위험 정도";
            this.sheetView1.Cells.Get(0, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(0, 2).BackColor = System.Drawing.Color.Gainsboro;
            this.sheetView1.Cells.Get(0, 2).Border = complexBorder3;
            this.sheetView1.Cells.Get(0, 2).CellType = textCellType3;
            this.sheetView1.Cells.Get(0, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.sheetView1.Cells.Get(0, 2).Locked = true;
            this.sheetView1.Cells.Get(0, 2).Value = "모니터링 빈도";
            this.sheetView1.Cells.Get(0, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(0, 3).BackColor = System.Drawing.Color.Gainsboro;
            this.sheetView1.Cells.Get(0, 3).Border = complexBorder4;
            this.sheetView1.Cells.Get(0, 3).CellType = textCellType4;
            this.sheetView1.Cells.Get(0, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.sheetView1.Cells.Get(0, 3).Locked = true;
            this.sheetView1.Cells.Get(0, 3).Value = "조치";
            this.sheetView1.Cells.Get(0, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(1, 0).BackColor = System.Drawing.Color.LightGreen;
            this.sheetView1.Cells.Get(1, 0).Border = complexBorder5;
            this.sheetView1.Cells.Get(1, 0).CellType = textCellType5;
            this.sheetView1.Cells.Get(1, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.sheetView1.Cells.Get(1, 0).Locked = true;
            this.sheetView1.Cells.Get(1, 0).Value = "0 ~ 4";
            this.sheetView1.Cells.Get(1, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(1, 1).BackColor = System.Drawing.Color.LightGreen;
            this.sheetView1.Cells.Get(1, 1).Border = complexBorder6;
            textCellType6.Multiline = true;
            textCellType6.Static = true;
            this.sheetView1.Cells.Get(1, 1).CellType = textCellType6;
            this.sheetView1.Cells.Get(1, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.sheetView1.Cells.Get(1, 1).Locked = true;
            this.sheetView1.Cells.Get(1, 1).Value = "경증\r\n(저위험군)";
            this.sheetView1.Cells.Get(1, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(1, 2).BackColor = System.Drawing.Color.LightGreen;
            this.sheetView1.Cells.Get(1, 2).Border = complexBorder7;
            this.sheetView1.Cells.Get(1, 2).CellType = textCellType7;
            this.sheetView1.Cells.Get(1, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.sheetView1.Cells.Get(1, 2).Locked = true;
            this.sheetView1.Cells.Get(1, 2).Value = "6시간 ~ 12시간";
            this.sheetView1.Cells.Get(1, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(1, 3).BackColor = System.Drawing.Color.LightGreen;
            this.sheetView1.Cells.Get(1, 3).Border = complexBorder8;
            this.sheetView1.Cells.Get(1, 3).CellType = textCellType8;
            this.sheetView1.Cells.Get(1, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.sheetView1.Cells.Get(1, 3).Locked = true;
            this.sheetView1.Cells.Get(1, 3).Value = " 대증치료 및 증상 경과 모니터링";
            this.sheetView1.Cells.Get(1, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(2, 0).BackColor = System.Drawing.Color.Orange;
            this.sheetView1.Cells.Get(2, 0).Border = complexBorder9;
            this.sheetView1.Cells.Get(2, 0).CellType = textCellType9;
            this.sheetView1.Cells.Get(2, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.sheetView1.Cells.Get(2, 0).Locked = true;
            this.sheetView1.Cells.Get(2, 0).Value = "5 ~ 6";
            this.sheetView1.Cells.Get(2, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(2, 1).BackColor = System.Drawing.Color.Orange;
            this.sheetView1.Cells.Get(2, 1).Border = complexBorder10;
            textCellType10.Multiline = true;
            this.sheetView1.Cells.Get(2, 1).CellType = textCellType10;
            this.sheetView1.Cells.Get(2, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.sheetView1.Cells.Get(2, 1).Locked = true;
            this.sheetView1.Cells.Get(2, 1).Value = "중등증\r\n(중증도위험군)";
            this.sheetView1.Cells.Get(2, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(2, 2).BackColor = System.Drawing.Color.Orange;
            this.sheetView1.Cells.Get(2, 2).Border = complexBorder11;
            this.sheetView1.Cells.Get(2, 2).CellType = textCellType11;
            this.sheetView1.Cells.Get(2, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.sheetView1.Cells.Get(2, 2).Locked = true;
            this.sheetView1.Cells.Get(2, 2).Value = "1~2시간";
            this.sheetView1.Cells.Get(2, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(2, 3).BackColor = System.Drawing.Color.Orange;
            this.sheetView1.Cells.Get(2, 3).Border = complexBorder12;
            this.sheetView1.Cells.Get(2, 3).CellType = textCellType12;
            this.sheetView1.Cells.Get(2, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.sheetView1.Cells.Get(2, 3).Locked = true;
            this.sheetView1.Cells.Get(2, 3).Value = " 대증치료 및 증상 경과 모니터링";
            this.sheetView1.Cells.Get(2, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(3, 0).BackColor = System.Drawing.Color.Red;
            this.sheetView1.Cells.Get(3, 0).Border = complexBorder13;
            this.sheetView1.Cells.Get(3, 0).CellType = textCellType13;
            this.sheetView1.Cells.Get(3, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.sheetView1.Cells.Get(3, 0).Locked = true;
            this.sheetView1.Cells.Get(3, 0).Value = "7이상";
            this.sheetView1.Cells.Get(3, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(3, 1).BackColor = System.Drawing.Color.Red;
            this.sheetView1.Cells.Get(3, 1).Border = complexBorder14;
            textCellType14.Multiline = true;
            this.sheetView1.Cells.Get(3, 1).CellType = textCellType14;
            this.sheetView1.Cells.Get(3, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.sheetView1.Cells.Get(3, 1).Locked = true;
            this.sheetView1.Cells.Get(3, 1).Value = "중증\r\n(고위험군)";
            this.sheetView1.Cells.Get(3, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(3, 2).BackColor = System.Drawing.Color.Red;
            this.sheetView1.Cells.Get(3, 2).Border = complexBorder15;
            this.sheetView1.Cells.Get(3, 2).CellType = textCellType15;
            this.sheetView1.Cells.Get(3, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.sheetView1.Cells.Get(3, 2).Locked = true;
            this.sheetView1.Cells.Get(3, 2).Value = "지속";
            this.sheetView1.Cells.Get(3, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Cells.Get(3, 3).BackColor = System.Drawing.Color.Red;
            this.sheetView1.Cells.Get(3, 3).Border = complexBorder16;
            this.sheetView1.Cells.Get(3, 3).CellType = textCellType16;
            this.sheetView1.Cells.Get(3, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.sheetView1.Cells.Get(3, 3).Locked = true;
            this.sheetView1.Cells.Get(3, 3).Value = " 기계호흡 등이 필요";
            this.sheetView1.Cells.Get(3, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.ColumnFooterSheetCornerStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.sheetView1.ColumnFooterSheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.sheetView1.ColumnFooterSheetCornerStyle.Parent = "CornerFooterDefaultEnhanced";
            this.sheetView1.ColumnFooterSheetCornerStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.sheetView1.ColumnHeader.Cells.Get(0, 0).Value = "변수";
            this.sheetView1.ColumnHeader.Cells.Get(0, 1).Value = "3";
            this.sheetView1.ColumnHeader.Cells.Get(0, 2).Value = "2";
            this.sheetView1.ColumnHeader.Cells.Get(0, 3).Value = "1";
            this.sheetView1.ColumnHeader.Visible = false;
            this.sheetView1.Columns.Get(0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.sheetView1.Columns.Get(0).Label = "변수";
            this.sheetView1.Columns.Get(0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.sheetView1.Columns.Get(1).Label = "3";
            this.sheetView1.Columns.Get(1).Width = 127F;
            this.sheetView1.Columns.Get(2).Label = "2";
            this.sheetView1.Columns.Get(2).Width = 107F;
            this.sheetView1.Columns.Get(3).Label = "1";
            this.sheetView1.Columns.Get(3).Width = 387F;
            this.sheetView1.FilterBarHeaderStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.sheetView1.FilterBarHeaderStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.sheetView1.FilterBarHeaderStyle.Parent = "RowHeaderDefaultEnhanced";
            this.sheetView1.FilterBarHeaderStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.sheetView1.RowHeader.Columns.Default.Resizable = false;
            this.sheetView1.RowHeader.Visible = false;
            this.sheetView1.Rows.Get(0).Height = 30F;
            this.sheetView1.Rows.Get(1).Height = 40F;
            this.sheetView1.Rows.Get(2).Height = 40F;
            this.sheetView1.Rows.Get(3).Height = 40F;
            this.sheetView1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // ssView
            // 
            this.ssView.AccessibleDescription = "ssView, Sheet1, Row 0, Column 0, 변수";
            this.ssView.Dock = System.Windows.Forms.DockStyle.Top;
            this.ssView.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.Never;
            this.ssView.Location = new System.Drawing.Point(0, 0);
            this.ssView.Name = "ssView";
            this.ssView.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.ssView_Sheet1});
            this.ssView.Size = new System.Drawing.Size(687, 225);
            this.ssView.TabIndex = 0;
            this.ssView.VerticalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.Never;
            // 
            // ssView_Sheet1
            // 
            this.ssView_Sheet1.Reset();
            this.ssView_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.ssView_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.ssView_Sheet1.ColumnCount = 8;
            this.ssView_Sheet1.RowCount = 7;
            this.ssView_Sheet1.Cells.Get(0, 0).BackColor = System.Drawing.Color.Gainsboro;
            this.ssView_Sheet1.Cells.Get(0, 0).Border = complexBorder17;
            this.ssView_Sheet1.Cells.Get(0, 0).CellType = textCellType17;
            this.ssView_Sheet1.Cells.Get(0, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 0).Locked = true;
            this.ssView_Sheet1.Cells.Get(0, 0).Value = "변수";
            this.ssView_Sheet1.Cells.Get(0, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 1).BackColor = System.Drawing.Color.Gainsboro;
            this.ssView_Sheet1.Cells.Get(0, 1).Border = complexBorder18;
            this.ssView_Sheet1.Cells.Get(0, 1).CellType = textCellType18;
            this.ssView_Sheet1.Cells.Get(0, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(0, 1).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 1).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 1).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.ssView_Sheet1.Cells.Get(0, 1).ParseFormatString = "n";
            this.ssView_Sheet1.Cells.Get(0, 1).Value = 3;
            this.ssView_Sheet1.Cells.Get(0, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 2).BackColor = System.Drawing.Color.Gainsboro;
            this.ssView_Sheet1.Cells.Get(0, 2).Border = complexBorder19;
            this.ssView_Sheet1.Cells.Get(0, 2).CellType = textCellType19;
            this.ssView_Sheet1.Cells.Get(0, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 2).Locked = true;
            this.ssView_Sheet1.Cells.Get(0, 2).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 2).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 2).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.ssView_Sheet1.Cells.Get(0, 2).ParseFormatString = "n";
            this.ssView_Sheet1.Cells.Get(0, 2).Value = 2;
            this.ssView_Sheet1.Cells.Get(0, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 3).BackColor = System.Drawing.Color.Gainsboro;
            this.ssView_Sheet1.Cells.Get(0, 3).Border = complexBorder20;
            this.ssView_Sheet1.Cells.Get(0, 3).CellType = textCellType20;
            this.ssView_Sheet1.Cells.Get(0, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 3).Locked = true;
            this.ssView_Sheet1.Cells.Get(0, 3).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 3).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 3).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.ssView_Sheet1.Cells.Get(0, 3).ParseFormatString = "n";
            this.ssView_Sheet1.Cells.Get(0, 3).Value = 1;
            this.ssView_Sheet1.Cells.Get(0, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 4).BackColor = System.Drawing.Color.Gainsboro;
            this.ssView_Sheet1.Cells.Get(0, 4).Border = complexBorder21;
            this.ssView_Sheet1.Cells.Get(0, 4).CellType = textCellType21;
            this.ssView_Sheet1.Cells.Get(0, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 4).Locked = true;
            this.ssView_Sheet1.Cells.Get(0, 4).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 4).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 4).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.ssView_Sheet1.Cells.Get(0, 4).ParseFormatString = "n";
            this.ssView_Sheet1.Cells.Get(0, 4).Value = 0;
            this.ssView_Sheet1.Cells.Get(0, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 5).BackColor = System.Drawing.Color.Gainsboro;
            this.ssView_Sheet1.Cells.Get(0, 5).Border = complexBorder22;
            this.ssView_Sheet1.Cells.Get(0, 5).CellType = textCellType22;
            this.ssView_Sheet1.Cells.Get(0, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 5).Locked = true;
            this.ssView_Sheet1.Cells.Get(0, 5).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 5).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 5).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.ssView_Sheet1.Cells.Get(0, 5).ParseFormatString = "n";
            this.ssView_Sheet1.Cells.Get(0, 5).Value = 1;
            this.ssView_Sheet1.Cells.Get(0, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 6).BackColor = System.Drawing.Color.Gainsboro;
            this.ssView_Sheet1.Cells.Get(0, 6).Border = complexBorder23;
            this.ssView_Sheet1.Cells.Get(0, 6).CellType = textCellType23;
            this.ssView_Sheet1.Cells.Get(0, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 6).Locked = true;
            this.ssView_Sheet1.Cells.Get(0, 6).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 6).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 6).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.ssView_Sheet1.Cells.Get(0, 6).ParseFormatString = "n";
            this.ssView_Sheet1.Cells.Get(0, 6).Value = 2;
            this.ssView_Sheet1.Cells.Get(0, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 7).BackColor = System.Drawing.Color.Gainsboro;
            this.ssView_Sheet1.Cells.Get(0, 7).Border = complexBorder24;
            this.ssView_Sheet1.Cells.Get(0, 7).CellType = textCellType24;
            this.ssView_Sheet1.Cells.Get(0, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(0, 7).Locked = true;
            this.ssView_Sheet1.Cells.Get(0, 7).ParseFormatInfo = ((System.Globalization.NumberFormatInfo)(cultureInfo.NumberFormat.Clone()));
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 7).ParseFormatInfo)).NumberDecimalDigits = 0;
            ((System.Globalization.NumberFormatInfo)(this.ssView_Sheet1.Cells.Get(0, 7).ParseFormatInfo)).NumberGroupSizes = new int[] {
        0};
            this.ssView_Sheet1.Cells.Get(0, 7).ParseFormatString = "n";
            this.ssView_Sheet1.Cells.Get(0, 7).Value = 3;
            this.ssView_Sheet1.Cells.Get(0, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 0).Border = complexBorder25;
            this.ssView_Sheet1.Cells.Get(1, 0).CellType = textCellType25;
            this.ssView_Sheet1.Cells.Get(1, 0).Locked = true;
            this.ssView_Sheet1.Cells.Get(1, 0).Value = "맥박(회/분)";
            this.ssView_Sheet1.Cells.Get(1, 1).Border = complexBorder26;
            this.ssView_Sheet1.Cells.Get(1, 1).CellType = textCellType26;
            this.ssView_Sheet1.Cells.Get(1, 1).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(1, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(1, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 2).Border = complexBorder27;
            this.ssView_Sheet1.Cells.Get(1, 2).CellType = textCellType27;
            this.ssView_Sheet1.Cells.Get(1, 2).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(1, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 2).Locked = true;
            this.ssView_Sheet1.Cells.Get(1, 2).Value = "<= 40";
            this.ssView_Sheet1.Cells.Get(1, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 3).Border = complexBorder28;
            this.ssView_Sheet1.Cells.Get(1, 3).CellType = textCellType28;
            this.ssView_Sheet1.Cells.Get(1, 3).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(1, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 3).Locked = true;
            this.ssView_Sheet1.Cells.Get(1, 3).Value = "41- 50";
            this.ssView_Sheet1.Cells.Get(1, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 4).Border = complexBorder29;
            this.ssView_Sheet1.Cells.Get(1, 4).CellType = textCellType29;
            this.ssView_Sheet1.Cells.Get(1, 4).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(1, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 4).Locked = true;
            this.ssView_Sheet1.Cells.Get(1, 4).Value = "51 - 100";
            this.ssView_Sheet1.Cells.Get(1, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 5).Border = complexBorder30;
            this.ssView_Sheet1.Cells.Get(1, 5).CellType = textCellType30;
            this.ssView_Sheet1.Cells.Get(1, 5).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(1, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 5).Locked = true;
            this.ssView_Sheet1.Cells.Get(1, 5).Value = "101- 110";
            this.ssView_Sheet1.Cells.Get(1, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 6).Border = complexBorder31;
            this.ssView_Sheet1.Cells.Get(1, 6).CellType = textCellType31;
            this.ssView_Sheet1.Cells.Get(1, 6).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(1, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 6).Locked = true;
            this.ssView_Sheet1.Cells.Get(1, 6).Value = "111-130";
            this.ssView_Sheet1.Cells.Get(1, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 7).Border = complexBorder32;
            this.ssView_Sheet1.Cells.Get(1, 7).CellType = textCellType32;
            this.ssView_Sheet1.Cells.Get(1, 7).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(1, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(1, 7).Locked = true;
            this.ssView_Sheet1.Cells.Get(1, 7).Value = ">= 131";
            this.ssView_Sheet1.Cells.Get(1, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 0).Border = complexBorder33;
            this.ssView_Sheet1.Cells.Get(2, 0).CellType = textCellType33;
            this.ssView_Sheet1.Cells.Get(2, 0).Locked = true;
            this.ssView_Sheet1.Cells.Get(2, 0).Value = "수축기 혈압 (mmHg)";
            this.ssView_Sheet1.Cells.Get(2, 1).Border = complexBorder34;
            this.ssView_Sheet1.Cells.Get(2, 1).CellType = textCellType34;
            this.ssView_Sheet1.Cells.Get(2, 1).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(2, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(2, 1).Value = "<= 70";
            this.ssView_Sheet1.Cells.Get(2, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 2).Border = complexBorder35;
            this.ssView_Sheet1.Cells.Get(2, 2).CellType = textCellType35;
            this.ssView_Sheet1.Cells.Get(2, 2).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(2, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 2).Locked = true;
            this.ssView_Sheet1.Cells.Get(2, 2).Value = "71 - 80";
            this.ssView_Sheet1.Cells.Get(2, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 3).Border = complexBorder36;
            this.ssView_Sheet1.Cells.Get(2, 3).CellType = textCellType36;
            this.ssView_Sheet1.Cells.Get(2, 3).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(2, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 3).Locked = true;
            this.ssView_Sheet1.Cells.Get(2, 3).Value = "81 - 100";
            this.ssView_Sheet1.Cells.Get(2, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 4).Border = complexBorder37;
            this.ssView_Sheet1.Cells.Get(2, 4).CellType = textCellType37;
            this.ssView_Sheet1.Cells.Get(2, 4).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(2, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 4).Locked = true;
            this.ssView_Sheet1.Cells.Get(2, 4).Value = "101 - 199";
            this.ssView_Sheet1.Cells.Get(2, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 5).Border = complexBorder38;
            this.ssView_Sheet1.Cells.Get(2, 5).CellType = textCellType38;
            this.ssView_Sheet1.Cells.Get(2, 5).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(2, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 5).Locked = true;
            this.ssView_Sheet1.Cells.Get(2, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 6).Border = complexBorder39;
            this.ssView_Sheet1.Cells.Get(2, 6).CellType = textCellType39;
            this.ssView_Sheet1.Cells.Get(2, 6).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(2, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 6).Locked = true;
            this.ssView_Sheet1.Cells.Get(2, 6).Value = ">= 200";
            this.ssView_Sheet1.Cells.Get(2, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 7).Border = complexBorder40;
            this.ssView_Sheet1.Cells.Get(2, 7).CellType = textCellType40;
            this.ssView_Sheet1.Cells.Get(2, 7).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(2, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(2, 7).Locked = true;
            this.ssView_Sheet1.Cells.Get(2, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 0).Border = complexBorder41;
            this.ssView_Sheet1.Cells.Get(3, 0).CellType = textCellType41;
            this.ssView_Sheet1.Cells.Get(3, 0).Locked = true;
            this.ssView_Sheet1.Cells.Get(3, 0).Value = "호흡수(회/분)";
            this.ssView_Sheet1.Cells.Get(3, 1).Border = complexBorder42;
            this.ssView_Sheet1.Cells.Get(3, 1).CellType = textCellType42;
            this.ssView_Sheet1.Cells.Get(3, 1).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(3, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(3, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 2).Border = complexBorder43;
            this.ssView_Sheet1.Cells.Get(3, 2).CellType = textCellType43;
            this.ssView_Sheet1.Cells.Get(3, 2).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(3, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 2).Locked = true;
            this.ssView_Sheet1.Cells.Get(3, 2).Value = "<= 8";
            this.ssView_Sheet1.Cells.Get(3, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 3).Border = complexBorder44;
            this.ssView_Sheet1.Cells.Get(3, 3).CellType = textCellType44;
            this.ssView_Sheet1.Cells.Get(3, 3).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(3, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 3).Locked = true;
            this.ssView_Sheet1.Cells.Get(3, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 4).Border = complexBorder45;
            this.ssView_Sheet1.Cells.Get(3, 4).CellType = textCellType45;
            this.ssView_Sheet1.Cells.Get(3, 4).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(3, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 4).Locked = true;
            this.ssView_Sheet1.Cells.Get(3, 4).Value = "9 - 14";
            this.ssView_Sheet1.Cells.Get(3, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 5).Border = complexBorder46;
            this.ssView_Sheet1.Cells.Get(3, 5).CellType = textCellType46;
            this.ssView_Sheet1.Cells.Get(3, 5).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(3, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 5).Locked = true;
            this.ssView_Sheet1.Cells.Get(3, 5).Value = "15 - 20";
            this.ssView_Sheet1.Cells.Get(3, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 6).Border = complexBorder47;
            this.ssView_Sheet1.Cells.Get(3, 6).CellType = textCellType47;
            this.ssView_Sheet1.Cells.Get(3, 6).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(3, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 6).Locked = true;
            this.ssView_Sheet1.Cells.Get(3, 6).Value = "21 - 29";
            this.ssView_Sheet1.Cells.Get(3, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 7).Border = complexBorder48;
            this.ssView_Sheet1.Cells.Get(3, 7).CellType = textCellType48;
            this.ssView_Sheet1.Cells.Get(3, 7).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(3, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(3, 7).Locked = true;
            this.ssView_Sheet1.Cells.Get(3, 7).Value = ">= 30";
            this.ssView_Sheet1.Cells.Get(3, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 0).Border = complexBorder49;
            this.ssView_Sheet1.Cells.Get(4, 0).CellType = textCellType49;
            this.ssView_Sheet1.Cells.Get(4, 0).Locked = true;
            this.ssView_Sheet1.Cells.Get(4, 0).Value = "체온(℃)";
            this.ssView_Sheet1.Cells.Get(4, 1).Border = complexBorder50;
            this.ssView_Sheet1.Cells.Get(4, 1).CellType = textCellType50;
            this.ssView_Sheet1.Cells.Get(4, 1).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(4, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(4, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 2).Border = complexBorder51;
            this.ssView_Sheet1.Cells.Get(4, 2).CellType = textCellType51;
            this.ssView_Sheet1.Cells.Get(4, 2).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(4, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 2).Locked = true;
            this.ssView_Sheet1.Cells.Get(4, 2).Value = "<= 35.0";
            this.ssView_Sheet1.Cells.Get(4, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 3).Border = complexBorder52;
            this.ssView_Sheet1.Cells.Get(4, 3).CellType = textCellType52;
            this.ssView_Sheet1.Cells.Get(4, 3).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(4, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 3).Locked = true;
            this.ssView_Sheet1.Cells.Get(4, 3).Value = "35.1 - 36.0";
            this.ssView_Sheet1.Cells.Get(4, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 4).Border = complexBorder53;
            this.ssView_Sheet1.Cells.Get(4, 4).CellType = textCellType53;
            this.ssView_Sheet1.Cells.Get(4, 4).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(4, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 4).Locked = true;
            this.ssView_Sheet1.Cells.Get(4, 4).Value = "36.1 - 37.4";
            this.ssView_Sheet1.Cells.Get(4, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 5).Border = complexBorder54;
            this.ssView_Sheet1.Cells.Get(4, 5).CellType = textCellType54;
            this.ssView_Sheet1.Cells.Get(4, 5).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(4, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 5).Locked = true;
            this.ssView_Sheet1.Cells.Get(4, 5).Value = ">= 37.5";
            this.ssView_Sheet1.Cells.Get(4, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 6).Border = complexBorder55;
            this.ssView_Sheet1.Cells.Get(4, 6).CellType = textCellType55;
            this.ssView_Sheet1.Cells.Get(4, 6).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(4, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 6).Locked = true;
            this.ssView_Sheet1.Cells.Get(4, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 7).Border = complexBorder56;
            this.ssView_Sheet1.Cells.Get(4, 7).CellType = textCellType56;
            this.ssView_Sheet1.Cells.Get(4, 7).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(4, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(4, 7).Locked = true;
            this.ssView_Sheet1.Cells.Get(4, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 0).Border = complexBorder57;
            this.ssView_Sheet1.Cells.Get(5, 0).CellType = textCellType57;
            this.ssView_Sheet1.Cells.Get(5, 0).Locked = true;
            this.ssView_Sheet1.Cells.Get(5, 0).Value = "AVPU SCORE";
            this.ssView_Sheet1.Cells.Get(5, 1).Border = complexBorder58;
            this.ssView_Sheet1.Cells.Get(5, 1).CellType = textCellType58;
            this.ssView_Sheet1.Cells.Get(5, 1).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(5, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(5, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 2).Border = complexBorder59;
            this.ssView_Sheet1.Cells.Get(5, 2).CellType = textCellType59;
            this.ssView_Sheet1.Cells.Get(5, 2).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(5, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 2).Locked = true;
            this.ssView_Sheet1.Cells.Get(5, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 3).Border = complexBorder60;
            this.ssView_Sheet1.Cells.Get(5, 3).CellType = textCellType60;
            this.ssView_Sheet1.Cells.Get(5, 3).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(5, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 3).Locked = true;
            this.ssView_Sheet1.Cells.Get(5, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 4).Border = complexBorder61;
            this.ssView_Sheet1.Cells.Get(5, 4).CellType = textCellType61;
            this.ssView_Sheet1.Cells.Get(5, 4).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(5, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 4).Locked = true;
            this.ssView_Sheet1.Cells.Get(5, 4).Value = "Alert";
            this.ssView_Sheet1.Cells.Get(5, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 5).Border = complexBorder62;
            textCellType62.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(5, 5).CellType = textCellType62;
            this.ssView_Sheet1.Cells.Get(5, 5).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(5, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 5).Locked = true;
            this.ssView_Sheet1.Cells.Get(5, 5).Value = "Verbal Response";
            this.ssView_Sheet1.Cells.Get(5, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 6).Border = complexBorder63;
            textCellType63.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(5, 6).CellType = textCellType63;
            this.ssView_Sheet1.Cells.Get(5, 6).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(5, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 6).Locked = true;
            this.ssView_Sheet1.Cells.Get(5, 6).Value = "Pain Response";
            this.ssView_Sheet1.Cells.Get(5, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 7).Border = complexBorder64;
            textCellType64.WordWrap = true;
            this.ssView_Sheet1.Cells.Get(5, 7).CellType = textCellType64;
            this.ssView_Sheet1.Cells.Get(5, 7).Font = new System.Drawing.Font("굴림", 9F);
            this.ssView_Sheet1.Cells.Get(5, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(5, 7).Locked = true;
            this.ssView_Sheet1.Cells.Get(5, 7).Value = "Unconsciousness\r\n";
            this.ssView_Sheet1.Cells.Get(5, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(6, 0).Border = complexBorder65;
            this.ssView_Sheet1.Cells.Get(6, 0).CellType = textCellType65;
            this.ssView_Sheet1.Cells.Get(6, 0).Font = new System.Drawing.Font("굴림", 16F, System.Drawing.FontStyle.Bold);
            this.ssView_Sheet1.Cells.Get(6, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(6, 0).Locked = true;
            this.ssView_Sheet1.Cells.Get(6, 0).Value = "총점";
            this.ssView_Sheet1.Cells.Get(6, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(6, 1).Border = complexBorder66;
            this.ssView_Sheet1.Cells.Get(6, 1).CellType = textCellType66;
            this.ssView_Sheet1.Cells.Get(6, 1).ColumnSpan = 7;
            this.ssView_Sheet1.Cells.Get(6, 1).Font = new System.Drawing.Font("굴림", 16F, System.Drawing.FontStyle.Bold);
            this.ssView_Sheet1.Cells.Get(6, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(6, 1).Locked = true;
            this.ssView_Sheet1.Cells.Get(6, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Cells.Get(6, 2).Border = complexBorder67;
            this.ssView_Sheet1.Cells.Get(6, 2).Font = new System.Drawing.Font("굴림", 12F, System.Drawing.FontStyle.Bold);
            this.ssView_Sheet1.Cells.Get(6, 2).Locked = true;
            this.ssView_Sheet1.Cells.Get(6, 3).Border = complexBorder68;
            this.ssView_Sheet1.Cells.Get(6, 3).Font = new System.Drawing.Font("굴림", 12F, System.Drawing.FontStyle.Bold);
            this.ssView_Sheet1.Cells.Get(6, 3).Locked = true;
            this.ssView_Sheet1.Cells.Get(6, 4).Border = complexBorder69;
            this.ssView_Sheet1.Cells.Get(6, 4).Font = new System.Drawing.Font("굴림", 12F, System.Drawing.FontStyle.Bold);
            this.ssView_Sheet1.Cells.Get(6, 4).Locked = true;
            this.ssView_Sheet1.Cells.Get(6, 5).Border = complexBorder70;
            this.ssView_Sheet1.Cells.Get(6, 5).Font = new System.Drawing.Font("굴림", 12F, System.Drawing.FontStyle.Bold);
            this.ssView_Sheet1.Cells.Get(6, 5).Locked = true;
            this.ssView_Sheet1.Cells.Get(6, 6).Border = complexBorder71;
            this.ssView_Sheet1.Cells.Get(6, 6).Font = new System.Drawing.Font("굴림", 12F, System.Drawing.FontStyle.Bold);
            this.ssView_Sheet1.Cells.Get(6, 6).Locked = true;
            this.ssView_Sheet1.Cells.Get(6, 7).Border = complexBorder72;
            this.ssView_Sheet1.Cells.Get(6, 7).Font = new System.Drawing.Font("굴림", 12F, System.Drawing.FontStyle.Bold);
            this.ssView_Sheet1.Cells.Get(6, 7).Locked = true;
            this.ssView_Sheet1.ColumnHeader.Cells.Get(0, 0).Value = "변수";
            this.ssView_Sheet1.ColumnHeader.Cells.Get(0, 1).Value = "3";
            this.ssView_Sheet1.ColumnHeader.Cells.Get(0, 2).Value = "2";
            this.ssView_Sheet1.ColumnHeader.Cells.Get(0, 3).Value = "1";
            this.ssView_Sheet1.ColumnHeader.Cells.Get(0, 4).Value = "0";
            this.ssView_Sheet1.ColumnHeader.Cells.Get(0, 5).Value = "1";
            this.ssView_Sheet1.ColumnHeader.Cells.Get(0, 6).Value = "2";
            this.ssView_Sheet1.ColumnHeader.Cells.Get(0, 7).Value = "3";
            this.ssView_Sheet1.ColumnHeader.Visible = false;
            this.ssView_Sheet1.Columns.Get(0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.ssView_Sheet1.Columns.Get(0).Label = "변수";
            this.ssView_Sheet1.Columns.Get(0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.ssView_Sheet1.Columns.Get(0).Width = 121F;
            this.ssView_Sheet1.Columns.Get(1).Label = "3";
            this.ssView_Sheet1.Columns.Get(1).Width = 80F;
            this.ssView_Sheet1.Columns.Get(2).Label = "2";
            this.ssView_Sheet1.Columns.Get(2).Width = 80F;
            this.ssView_Sheet1.Columns.Get(3).Label = "1";
            this.ssView_Sheet1.Columns.Get(3).Width = 80F;
            this.ssView_Sheet1.Columns.Get(4).Label = "0";
            this.ssView_Sheet1.Columns.Get(4).Width = 80F;
            this.ssView_Sheet1.Columns.Get(5).Label = "1";
            this.ssView_Sheet1.Columns.Get(5).Width = 80F;
            this.ssView_Sheet1.Columns.Get(6).Label = "2";
            this.ssView_Sheet1.Columns.Get(6).Width = 80F;
            this.ssView_Sheet1.Columns.Get(7).Label = "3";
            this.ssView_Sheet1.Columns.Get(7).Width = 80F;
            this.ssView_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.ssView_Sheet1.RowHeader.Visible = false;
            this.ssView_Sheet1.Rows.Get(0).Height = 30F;
            this.ssView_Sheet1.Rows.Get(1).Height = 30F;
            this.ssView_Sheet1.Rows.Get(2).Height = 30F;
            this.ssView_Sheet1.Rows.Get(3).Height = 30F;
            this.ssView_Sheet1.Rows.Get(4).Height = 30F;
            this.ssView_Sheet1.Rows.Get(5).Height = 35F;
            this.ssView_Sheet1.Rows.Get(6).Height = 35F;
            this.ssView_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // frmEmrBaseRRSDetail
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(687, 379);
            this.Controls.Add(this.panMain);
            this.Name = "frmEmrBaseRRSDetail";
            this.Text = "RRS 스코어 상세 보기";
            this.Load += new System.EventHandler(this.frmEmrBaseRRSDetail_Load);
            this.panMain.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.fpSpread1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.sheetView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ssView_Sheet1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panMain;
        private FarPoint.Win.Spread.FpSpread ssView;
        private FarPoint.Win.Spread.SheetView ssView_Sheet1;
        private FarPoint.Win.Spread.FpSpread fpSpread1;
        private FarPoint.Win.Spread.SheetView sheetView1;
    }
}