namespace ComHpcLibB
{
    partial class frmHaPrintFoodTicket
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            FarPoint.Win.Spread.NamedStyle namedStyle1 = new FarPoint.Win.Spread.NamedStyle("Color798637307688945720637", "DataAreaDefault");
            FarPoint.Win.Spread.NamedStyle namedStyle2 = new FarPoint.Win.Spread.NamedStyle("Text1131637307688945740590", "DataAreaDefault");
            FarPoint.Win.Spread.CellType.TextCellType textCellType1 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle3 = new FarPoint.Win.Spread.NamedStyle("Font1471637307688945780477");
            FarPoint.Win.Spread.NamedStyle namedStyle4 = new FarPoint.Win.Spread.NamedStyle("Text1497637307688945780477");
            FarPoint.Win.Spread.CellType.TextCellType textCellType2 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle5 = new FarPoint.Win.Spread.NamedStyle("Font1548637307688945790459");
            FarPoint.Win.Spread.NamedStyle namedStyle6 = new FarPoint.Win.Spread.NamedStyle("Static1680637307688945810399");
            FarPoint.Win.Spread.CellType.TextCellType textCellType3 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle7 = new FarPoint.Win.Spread.NamedStyle("Font1714637307688945820372");
            FarPoint.Win.Spread.NamedStyle namedStyle8 = new FarPoint.Win.Spread.NamedStyle("Font1773637307688945820372");
            FarPoint.Win.Spread.NamedStyle namedStyle9 = new FarPoint.Win.Spread.NamedStyle("Font2248637307688945930077");
            FarPoint.Win.Spread.NamedStyle namedStyle10 = new FarPoint.Win.Spread.NamedStyle("Static2266637307688945930077");
            FarPoint.Win.Spread.CellType.TextCellType textCellType4 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle11 = new FarPoint.Win.Spread.NamedStyle("Static2284637307688945940052");
            FarPoint.Win.Spread.CellType.TextCellType textCellType5 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle12 = new FarPoint.Win.Spread.NamedStyle("Font2372637307688945960004");
            FarPoint.Win.Spread.NamedStyle namedStyle13 = new FarPoint.Win.Spread.NamedStyle("Text2398637307688945960004");
            FarPoint.Win.Spread.CellType.TextCellType textCellType6 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle14 = new FarPoint.Win.Spread.NamedStyle("Font2504637307688945960004");
            FarPoint.Win.Spread.NamedStyle namedStyle15 = new FarPoint.Win.Spread.NamedStyle("Text2615637307688945969982");
            FarPoint.Win.Spread.CellType.TextCellType textCellType7 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle16 = new FarPoint.Win.Spread.NamedStyle("Static2834637307688945989947");
            FarPoint.Win.Spread.CellType.TextCellType textCellType8 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle17 = new FarPoint.Win.Spread.NamedStyle("Text2894637307688945999897");
            FarPoint.Win.Spread.CellType.TextCellType textCellType9 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle18 = new FarPoint.Win.Spread.NamedStyle("Font3108637307688946079793");
            FarPoint.Win.Spread.NamedStyle namedStyle19 = new FarPoint.Win.Spread.NamedStyle("Static3126637307688946079793");
            FarPoint.Win.Spread.CellType.TextCellType textCellType10 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle20 = new FarPoint.Win.Spread.NamedStyle("Font3171637307688946089653");
            FarPoint.Win.Spread.NamedStyle namedStyle21 = new FarPoint.Win.Spread.NamedStyle("Static3189637307688946089653");
            FarPoint.Win.Spread.CellType.TextCellType textCellType11 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle22 = new FarPoint.Win.Spread.NamedStyle("Empty19022637307688946159465");
            FarPoint.Win.Spread.CellType.EmptyCellType emptyCellType1 = new FarPoint.Win.Spread.CellType.EmptyCellType();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmHaPrintFoodTicket));
            FarPoint.Win.Spread.NamedStyle namedStyle23 = new FarPoint.Win.Spread.NamedStyle("Text110637307688946179416");
            FarPoint.Win.Spread.CellType.TextCellType textCellType12 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle24 = new FarPoint.Win.Spread.NamedStyle("Text233637307688946189386");
            FarPoint.Win.Spread.CellType.TextCellType textCellType13 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.TipAppearance tipAppearance1 = new FarPoint.Win.Spread.TipAppearance();
            FarPoint.Win.Spread.CellType.TextCellType textCellType14 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder1 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder2 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder3 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder4 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder5 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder6 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder7 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder8 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder9 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.Spread.CellType.TextCellType textCellType15 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.ComplexBorder complexBorder10 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder11 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder12 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder13 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder14 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder15 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder16 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder17 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder18 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder19 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder20 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder21 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.Dotted, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder22 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.Dotted, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder23 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.Dotted, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder24 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.Dotted, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder25 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.Dotted, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder26 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.Dotted, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder27 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.Dotted, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder28 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.Dotted, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder29 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.Dotted, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder30 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.Dotted, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder31 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder32 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder33 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder34 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder35 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.ComplexBorder complexBorder36 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.ThinLine, System.Drawing.Color.Black), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.Spread.NoPrinterPrintInfo noPrinterPrintInfo1 = new FarPoint.Win.Spread.NoPrinterPrintInfo();
            this.SSFoodTicket = new FarPoint.Win.Spread.FpSpread();
            this.SSFoodTicket_Sheet1 = new FarPoint.Win.Spread.SheetView();
            ((System.ComponentModel.ISupportInitialize)(this.SSFoodTicket)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.SSFoodTicket_Sheet1)).BeginInit();
            this.SuspendLayout();
            // 
            // SSFoodTicket
            // 
            this.SSFoodTicket.AccessibleDescription = "SSFoodTicket, Sheet1, Row 0, Column 0, ";
            this.SSFoodTicket.AllowCellOverflow = true;
            this.SSFoodTicket.AllowEditOverflow = true;
            this.SSFoodTicket.Dock = System.Windows.Forms.DockStyle.Fill;
            this.SSFoodTicket.Location = new System.Drawing.Point(0, 0);
            this.SSFoodTicket.Name = "SSFoodTicket";
            namedStyle1.Font = new System.Drawing.Font("굴림", 9F);
            namedStyle1.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle1.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle1.Parent = "DataAreaDefault";
            namedStyle1.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            textCellType1.MaxLength = 60;
            namedStyle2.CellType = textCellType1;
            namedStyle2.Font = new System.Drawing.Font("굴림", 9F);
            namedStyle2.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle2.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle2.Parent = "DataAreaDefault";
            namedStyle2.Renderer = textCellType1;
            namedStyle2.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            namedStyle3.Font = new System.Drawing.Font("맑은 고딕", 18F, System.Drawing.FontStyle.Bold);
            namedStyle3.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle3.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle3.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            textCellType2.MaxLength = 60;
            namedStyle4.CellType = textCellType2;
            namedStyle4.Font = new System.Drawing.Font("맑은 고딕", 18F, System.Drawing.FontStyle.Bold);
            namedStyle4.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle4.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle4.Renderer = textCellType2;
            namedStyle4.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle5.Font = new System.Drawing.Font("맑은 고딕", 14F);
            namedStyle5.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle5.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle5.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            textCellType3.Static = true;
            namedStyle6.CellType = textCellType3;
            namedStyle6.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            namedStyle6.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle6.Renderer = textCellType3;
            namedStyle6.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle7.Font = new System.Drawing.Font("굴림체", 14F);
            namedStyle7.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle7.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle7.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            namedStyle8.Font = new System.Drawing.Font("굴림체", 12F);
            namedStyle8.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle8.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle8.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            namedStyle9.Font = new System.Drawing.Font("굴림체", 11F);
            namedStyle9.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle9.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle9.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            textCellType4.Static = true;
            textCellType4.StringTrim = System.Drawing.StringTrimming.EllipsisCharacter;
            textCellType4.WordWrap = true;
            namedStyle10.CellType = textCellType4;
            namedStyle10.Font = new System.Drawing.Font("굴림체", 11F);
            namedStyle10.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            namedStyle10.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle10.Renderer = textCellType4;
            namedStyle10.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Top;
            textCellType5.Static = true;
            textCellType5.WordWrap = true;
            namedStyle11.CellType = textCellType5;
            namedStyle11.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            namedStyle11.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle11.Renderer = textCellType5;
            namedStyle11.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Top;
            namedStyle12.Font = new System.Drawing.Font("굴림", 12F);
            namedStyle12.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle12.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle12.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            textCellType6.MaxLength = 300;
            namedStyle13.CellType = textCellType6;
            namedStyle13.Font = new System.Drawing.Font("굴림", 12F);
            namedStyle13.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle13.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle13.Renderer = textCellType6;
            namedStyle13.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle14.Font = new System.Drawing.Font("굴림", 14F);
            namedStyle14.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle14.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle14.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            textCellType7.MaxLength = 200;
            namedStyle15.CellType = textCellType7;
            namedStyle15.Font = new System.Drawing.Font("굴림", 12F);
            namedStyle15.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle15.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle15.Renderer = textCellType7;
            namedStyle15.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType8.Static = true;
            namedStyle16.CellType = textCellType8;
            namedStyle16.Font = new System.Drawing.Font("굴림", 12F);
            namedStyle16.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            namedStyle16.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle16.Renderer = textCellType8;
            namedStyle16.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType9.MaxLength = 60;
            namedStyle17.CellType = textCellType9;
            namedStyle17.Font = new System.Drawing.Font("굴림", 14F);
            namedStyle17.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle17.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle17.Renderer = textCellType9;
            namedStyle17.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle18.Font = new System.Drawing.Font("굴림", 20F);
            namedStyle18.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle18.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle18.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            textCellType10.Static = true;
            namedStyle19.CellType = textCellType10;
            namedStyle19.Font = new System.Drawing.Font("굴림", 20F);
            namedStyle19.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            namedStyle19.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle19.Renderer = textCellType10;
            namedStyle19.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle20.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold);
            namedStyle20.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle20.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle20.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            textCellType11.Static = true;
            namedStyle21.CellType = textCellType11;
            namedStyle21.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold);
            namedStyle21.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            namedStyle21.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle21.Renderer = textCellType11;
            namedStyle21.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            emptyCellType1.BackgroundImage = new FarPoint.Win.Picture(((System.Drawing.Image)(resources.GetObject("emptyCellType1.BackgroundImage"))), FarPoint.Win.RenderStyle.StretchAndScale, System.Drawing.Color.Empty, 0, FarPoint.Win.HorizontalAlignment.Center, FarPoint.Win.VerticalAlignment.Center);
            namedStyle22.CellType = emptyCellType1;
            namedStyle22.Font = new System.Drawing.Font("굴림", 12F);
            namedStyle22.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle22.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle22.Renderer = emptyCellType1;
            namedStyle22.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType12.MaxLength = 100;
            namedStyle23.CellType = textCellType12;
            namedStyle23.Font = new System.Drawing.Font("굴림", 12F);
            namedStyle23.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle23.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle23.Renderer = textCellType12;
            namedStyle23.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            textCellType13.MaxLength = 100;
            namedStyle24.CellType = textCellType13;
            namedStyle24.Font = new System.Drawing.Font("굴림", 12F);
            namedStyle24.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            namedStyle24.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle24.Renderer = textCellType13;
            namedStyle24.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket.NamedStyles.AddRange(new FarPoint.Win.Spread.NamedStyle[] {
            namedStyle1,
            namedStyle2,
            namedStyle3,
            namedStyle4,
            namedStyle5,
            namedStyle6,
            namedStyle7,
            namedStyle8,
            namedStyle9,
            namedStyle10,
            namedStyle11,
            namedStyle12,
            namedStyle13,
            namedStyle14,
            namedStyle15,
            namedStyle16,
            namedStyle17,
            namedStyle18,
            namedStyle19,
            namedStyle20,
            namedStyle21,
            namedStyle22,
            namedStyle23,
            namedStyle24});
            this.SSFoodTicket.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.SSFoodTicket_Sheet1});
            this.SSFoodTicket.Size = new System.Drawing.Size(303, 488);
            this.SSFoodTicket.TabIndex = 2;
            this.SSFoodTicket.TabStripRatio = 0.6D;
            tipAppearance1.BackColor = System.Drawing.SystemColors.Info;
            tipAppearance1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F);
            tipAppearance1.ForeColor = System.Drawing.SystemColors.InfoText;
            this.SSFoodTicket.TextTipAppearance = tipAppearance1;
            // 
            // SSFoodTicket_Sheet1
            // 
            this.SSFoodTicket_Sheet1.Reset();
            this.SSFoodTicket_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.SSFoodTicket_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.SSFoodTicket_Sheet1.ColumnCount = 10;
            this.SSFoodTicket_Sheet1.RowCount = 26;
            textCellType14.MaxLength = 60;
            this.SSFoodTicket_Sheet1.Cells.Get(1, 1).CellType = textCellType14;
            this.SSFoodTicket_Sheet1.Cells.Get(1, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(1, 1).Font = new System.Drawing.Font("맑은 고딕", 15F, System.Drawing.FontStyle.Bold);
            this.SSFoodTicket_Sheet1.Cells.Get(1, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(1, 1).Value = "식사 이용권";
            this.SSFoodTicket_Sheet1.Cells.Get(1, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(1, 2).StyleName = "Font1548637307688945790459";
            this.SSFoodTicket_Sheet1.Cells.Get(1, 3).StyleName = "Font1548637307688945790459";
            this.SSFoodTicket_Sheet1.Cells.Get(1, 4).StyleName = "Font1548637307688945790459";
            this.SSFoodTicket_Sheet1.Cells.Get(1, 5).StyleName = "Font1548637307688945790459";
            this.SSFoodTicket_Sheet1.Cells.Get(1, 6).StyleName = "Font1548637307688945790459";
            this.SSFoodTicket_Sheet1.Cells.Get(1, 7).StyleName = "Font1548637307688945790459";
            this.SSFoodTicket_Sheet1.Cells.Get(1, 8).StyleName = "Font1548637307688945790459";
            this.SSFoodTicket_Sheet1.Cells.Get(2, 0).Border = complexBorder1;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 1).Border = complexBorder2;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 1).ColumnSpan = 2;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 1).Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.SSFoodTicket_Sheet1.Cells.Get(2, 1).Value = "성      명:";
            this.SSFoodTicket_Sheet1.Cells.Get(2, 2).Border = complexBorder3;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 3).Border = complexBorder4;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 3).ColumnSpan = 6;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 3).Font = new System.Drawing.Font("맑은 고딕", 12F, System.Drawing.FontStyle.Bold);
            this.SSFoodTicket_Sheet1.Cells.Get(2, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 4).Border = complexBorder5;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 5).Border = complexBorder6;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 6).Border = complexBorder7;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 7).Border = complexBorder8;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 8).Border = complexBorder9;
            textCellType15.Static = true;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 8).CellType = textCellType15;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(2, 9).Border = complexBorder10;
            this.SSFoodTicket_Sheet1.Cells.Get(3, 1).ColumnSpan = 2;
            this.SSFoodTicket_Sheet1.Cells.Get(3, 1).Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.SSFoodTicket_Sheet1.Cells.Get(3, 1).Value = "검진일자:";
            this.SSFoodTicket_Sheet1.Cells.Get(3, 2).StyleName = "Font1714637307688945820372";
            this.SSFoodTicket_Sheet1.Cells.Get(3, 3).ColumnSpan = 6;
            this.SSFoodTicket_Sheet1.Cells.Get(3, 3).Font = new System.Drawing.Font("맑은 고딕", 12F, System.Drawing.FontStyle.Bold);
            this.SSFoodTicket_Sheet1.Cells.Get(3, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 0).Border = complexBorder11;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 1).Border = complexBorder12;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 1).Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.SSFoodTicket_Sheet1.Cells.Get(4, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 1).Value = "[참가득그린푸드 ☎278-0166]";
            this.SSFoodTicket_Sheet1.Cells.Get(4, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 2).Border = complexBorder13;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 2).Font = new System.Drawing.Font("굴림체", 12F);
            this.SSFoodTicket_Sheet1.Cells.Get(4, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 3).Border = complexBorder14;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 3).Font = new System.Drawing.Font("굴림체", 12F);
            this.SSFoodTicket_Sheet1.Cells.Get(4, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 4).Border = complexBorder15;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 4).Font = new System.Drawing.Font("굴림체", 12F);
            this.SSFoodTicket_Sheet1.Cells.Get(4, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 5).Border = complexBorder16;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 5).Font = new System.Drawing.Font("굴림체", 12F);
            this.SSFoodTicket_Sheet1.Cells.Get(4, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 6).Border = complexBorder17;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 6).Font = new System.Drawing.Font("굴림체", 12F);
            this.SSFoodTicket_Sheet1.Cells.Get(4, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 7).Border = complexBorder18;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 7).Font = new System.Drawing.Font("굴림체", 12F);
            this.SSFoodTicket_Sheet1.Cells.Get(4, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 8).Border = complexBorder19;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 8).Font = new System.Drawing.Font("굴림체", 12F);
            this.SSFoodTicket_Sheet1.Cells.Get(4, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(4, 9).Border = complexBorder20;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 1).Value = "□된장뚝배기        □순두부백반";
            this.SSFoodTicket_Sheet1.Cells.Get(5, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(5, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 1).Value = "□돌솥비빔밥        □콩나물국밥";
            this.SSFoodTicket_Sheet1.Cells.Get(6, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(6, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 1).Value = "□소고기육개장     □돈까스정식";
            this.SSFoodTicket_Sheet1.Cells.Get(7, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(7, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 1).Value = "□제육덮밥";
            this.SSFoodTicket_Sheet1.Cells.Get(8, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(8, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(9, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(9, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(9, 1).Value = "★ 포장 시 용기료 무료 ★";
            this.SSFoodTicket_Sheet1.Cells.Get(9, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 0).Border = complexBorder21;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 0).Locked = false;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 1).Border = complexBorder22;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 1).Locked = false;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 2).Border = complexBorder23;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 2).Locked = false;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 3).Border = complexBorder24;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 3).Locked = false;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 4).Border = complexBorder25;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 4).Locked = false;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 5).Border = complexBorder26;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 5).Locked = false;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 6).Border = complexBorder27;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 6).Locked = false;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 7).Border = complexBorder28;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 7).Locked = false;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 8).Border = complexBorder29;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 8).Locked = false;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 9).Border = complexBorder30;
            this.SSFoodTicket_Sheet1.Cells.Get(10, 9).Locked = false;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 1).Font = new System.Drawing.Font("맑은 고딕", 11F, System.Drawing.FontStyle.Bold);
            this.SSFoodTicket_Sheet1.Cells.Get(11, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 1).Value = "[죽이야기 ☎275-6288]";
            this.SSFoodTicket_Sheet1.Cells.Get(11, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(11, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 1).Value = "□한우야채죽       □마죽";
            this.SSFoodTicket_Sheet1.Cells.Get(12, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(12, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 1).Value = "□인삼닭죽          □홍합미역죽";
            this.SSFoodTicket_Sheet1.Cells.Get(13, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(13, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 1).Value = "□흑임자죽          □야채죽";
            this.SSFoodTicket_Sheet1.Cells.Get(14, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(14, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 1).Value = "□버섯야채죽       □참치야채죽";
            this.SSFoodTicket_Sheet1.Cells.Get(15, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(15, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 1).Value = "□황태콩나물죽    □호박죽";
            this.SSFoodTicket_Sheet1.Cells.Get(16, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.SSFoodTicket_Sheet1.Cells.Get(16, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(17, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(17, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(17, 1).Value = "★ 포장 시 용기료 무료 ★";
            this.SSFoodTicket_Sheet1.Cells.Get(17, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(17, 2).StyleName = "Font1714637307688945820372";
            this.SSFoodTicket_Sheet1.Cells.Get(19, 1).ColumnSpan = 2;
            this.SSFoodTicket_Sheet1.Cells.Get(19, 1).Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.SSFoodTicket_Sheet1.Cells.Get(19, 1).Value = "유효기간:";
            this.SSFoodTicket_Sheet1.Cells.Get(19, 2).Font = new System.Drawing.Font("굴림체", 14F);
            this.SSFoodTicket_Sheet1.Cells.Get(19, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(19, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(19, 3).ColumnSpan = 6;
            this.SSFoodTicket_Sheet1.Cells.Get(19, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(19, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(19, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(19, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(19, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(19, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(19, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(19, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(19, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(19, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(20, 0).Border = complexBorder31;
            this.SSFoodTicket_Sheet1.Cells.Get(20, 1).Border = complexBorder32;
            this.SSFoodTicket_Sheet1.Cells.Get(20, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(20, 1).Font = new System.Drawing.Font("맑은 고딕", 12F, System.Drawing.FontStyle.Bold);
            this.SSFoodTicket_Sheet1.Cells.Get(20, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(20, 1).Value = "포항성모병원 건강증진센터";
            this.SSFoodTicket_Sheet1.Cells.Get(20, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(20, 2).StyleName = "Font1773637307688945820372";
            this.SSFoodTicket_Sheet1.Cells.Get(20, 4).StyleName = "Static2266637307688945930077";
            this.SSFoodTicket_Sheet1.Cells.Get(20, 5).StyleName = "Static2284637307688945940052";
            this.SSFoodTicket_Sheet1.Cells.Get(20, 6).StyleName = "Static2284637307688945940052";
            this.SSFoodTicket_Sheet1.Cells.Get(20, 7).StyleName = "Static2284637307688945940052";
            this.SSFoodTicket_Sheet1.Cells.Get(20, 8).StyleName = "Static2284637307688945940052";
            this.SSFoodTicket_Sheet1.Cells.Get(20, 9).Border = complexBorder33;
            this.SSFoodTicket_Sheet1.Cells.Get(21, 0).Border = complexBorder34;
            this.SSFoodTicket_Sheet1.Cells.Get(21, 1).Border = complexBorder35;
            this.SSFoodTicket_Sheet1.Cells.Get(21, 1).ColumnSpan = 8;
            this.SSFoodTicket_Sheet1.Cells.Get(21, 1).Font = new System.Drawing.Font("맑은 고딕", 12F, System.Drawing.FontStyle.Bold);
            this.SSFoodTicket_Sheet1.Cells.Get(21, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(21, 1).Value = "■식당장소: 본관 지하 1층";
            this.SSFoodTicket_Sheet1.Cells.Get(21, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.SSFoodTicket_Sheet1.Cells.Get(21, 9).Border = complexBorder36;
            this.SSFoodTicket_Sheet1.Cells.Get(25, 1).StyleName = "Text2398637307688945960004";
            this.SSFoodTicket_Sheet1.Cells.Get(25, 2).StyleName = "Font2504637307688945960004";
            this.SSFoodTicket_Sheet1.ColumnFooter.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.SSFoodTicket_Sheet1.ColumnFooterSheetCornerStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.SSFoodTicket_Sheet1.ColumnFooterSheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.SSFoodTicket_Sheet1.ColumnFooterSheetCornerStyle.Parent = "CornerFooterDefaultEnhanced";
            this.SSFoodTicket_Sheet1.ColumnFooterSheetCornerStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.SSFoodTicket_Sheet1.ColumnHeader.AutoText = FarPoint.Win.Spread.HeaderAutoText.Numbers;
            this.SSFoodTicket_Sheet1.ColumnHeader.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.SSFoodTicket_Sheet1.ColumnHeader.Visible = false;
            this.SSFoodTicket_Sheet1.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.SSFoodTicket_Sheet1.Columns.Get(0).Width = 6F;
            this.SSFoodTicket_Sheet1.Columns.Get(1).Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.SSFoodTicket_Sheet1.Columns.Get(1).Width = 33F;
            this.SSFoodTicket_Sheet1.Columns.Get(2).Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.SSFoodTicket_Sheet1.Columns.Get(2).Width = 33F;
            this.SSFoodTicket_Sheet1.Columns.Get(3).Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.SSFoodTicket_Sheet1.Columns.Get(3).Width = 33F;
            this.SSFoodTicket_Sheet1.Columns.Get(4).Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.SSFoodTicket_Sheet1.Columns.Get(4).Width = 33F;
            this.SSFoodTicket_Sheet1.Columns.Get(5).Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.SSFoodTicket_Sheet1.Columns.Get(5).Width = 33F;
            this.SSFoodTicket_Sheet1.Columns.Get(6).Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.SSFoodTicket_Sheet1.Columns.Get(6).Width = 33F;
            this.SSFoodTicket_Sheet1.Columns.Get(7).Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.SSFoodTicket_Sheet1.Columns.Get(7).Width = 33F;
            this.SSFoodTicket_Sheet1.Columns.Get(8).Font = new System.Drawing.Font("맑은 고딕", 10F);
            this.SSFoodTicket_Sheet1.Columns.Get(8).Width = 33F;
            this.SSFoodTicket_Sheet1.Columns.Get(9).Width = 4F;
            this.SSFoodTicket_Sheet1.DefaultStyleName = "Text1131637307688945740590";
            this.SSFoodTicket_Sheet1.FilterBarHeaderStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.SSFoodTicket_Sheet1.FilterBarHeaderStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.SSFoodTicket_Sheet1.FilterBarHeaderStyle.Parent = "RowHeaderDefaultEnhanced";
            this.SSFoodTicket_Sheet1.FilterBarHeaderStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.SSFoodTicket_Sheet1.HorizontalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.None);
            this.SSFoodTicket_Sheet1.PrintInfo.ColEnd = 0;
            this.SSFoodTicket_Sheet1.PrintInfo.ColStart = 0;
            this.SSFoodTicket_Sheet1.PrintInfo.JobName = "Spread";
            noPrinterPrintInfo1.Bounds = new System.Drawing.Rectangle(0, 0, 816, 11);
            noPrinterPrintInfo1.HardMarginX = 0F;
            noPrinterPrintInfo1.HardMarginY = 0F;
            noPrinterPrintInfo1.SupportColor = true;
            this.SSFoodTicket_Sheet1.PrintInfo.NoPrinterSetting = noPrinterPrintInfo1;
            this.SSFoodTicket_Sheet1.PrintInfo.PageEnd = 1;
            this.SSFoodTicket_Sheet1.PrintInfo.PageStart = 0;
            this.SSFoodTicket_Sheet1.PrintInfo.PdfSecurity = null;
            this.SSFoodTicket_Sheet1.PrintInfo.RowEnd = 0;
            this.SSFoodTicket_Sheet1.PrintInfo.RowStart = 0;
            this.SSFoodTicket_Sheet1.PrintInfo.ShowColumnHeader = FarPoint.Win.Spread.PrintHeader.Show;
            this.SSFoodTicket_Sheet1.PrintInfo.ShowRowHeader = FarPoint.Win.Spread.PrintHeader.Show;
            this.SSFoodTicket_Sheet1.PrintInfo.ZoomFactor = 1F;
            this.SSFoodTicket_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.SSFoodTicket_Sheet1.RowHeader.Columns.Get(0).Width = 38F;
            this.SSFoodTicket_Sheet1.RowHeader.Visible = false;
            this.SSFoodTicket_Sheet1.Rows.Get(0).Height = 7F;
            this.SSFoodTicket_Sheet1.Rows.Get(1).Height = 28F;
            this.SSFoodTicket_Sheet1.Rows.Get(2).Height = 24F;
            this.SSFoodTicket_Sheet1.Rows.Get(3).Height = 24F;
            this.SSFoodTicket_Sheet1.Rows.Get(4).Height = 25F;
            this.SSFoodTicket_Sheet1.Rows.Get(5).Height = 22F;
            this.SSFoodTicket_Sheet1.Rows.Get(6).Height = 22F;
            this.SSFoodTicket_Sheet1.Rows.Get(8).Height = 22F;
            this.SSFoodTicket_Sheet1.Rows.Get(11).Height = 25F;
            this.SSFoodTicket_Sheet1.Rows.Get(16).Height = 22F;
            this.SSFoodTicket_Sheet1.Rows.Get(18).Height = 22F;
            this.SSFoodTicket_Sheet1.Rows.Get(19).Height = 22F;
            this.SSFoodTicket_Sheet1.Rows.Get(20).Height = 30F;
            this.SSFoodTicket_Sheet1.Rows.Get(21).Height = 30F;
            this.SSFoodTicket_Sheet1.Rows.Get(22).Height = 10F;
            this.SSFoodTicket_Sheet1.Rows.Get(23).Height = 10F;
            this.SSFoodTicket_Sheet1.Rows.Get(24).Height = 10F;
            this.SSFoodTicket_Sheet1.Rows.Get(25).Height = 10F;
            this.SSFoodTicket_Sheet1.VerticalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.None);
            this.SSFoodTicket_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // frmHaPrintFoodTicket
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 17F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(303, 488);
            this.Controls.Add(this.SSFoodTicket);
            this.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.Name = "frmHaPrintFoodTicket";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmHaPrintFoodTicket";
            ((System.ComponentModel.ISupportInitialize)(this.SSFoodTicket)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.SSFoodTicket_Sheet1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private FarPoint.Win.Spread.FpSpread SSFoodTicket;
        private FarPoint.Win.Spread.SheetView SSFoodTicket_Sheet1;
    }
}